- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/user.spec.ts
- src/uistatic/scripts/dependencies.ts
Remove access fields from tests, uistatic - these should have been part of https://github.com/uProxy/uproxy/pull/762
Tested in grunt test, chrome, firefox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/767)
> Remove access fields from tests, uistatic

- src/generic_core/social.spec.ts
- src/generic_core/social.ts
- src/generic_core/user.spec.ts
- src/generic_core/user.ts
- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/instance.html
- src/generic_ui/polymer/roster-group.html
- src/generic_ui/polymer/roster.html
- src/generic_ui/polymer/roster.ts
- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/ui.ts
- src/generic_ui/scripts/user.spec.ts
- src/generic_ui/scripts/user.ts
- src/interfaces/ui.d.ts
- src/uistatic/scripts/dependencies.ts
Fix for https://github.com/uProxy/uproxy/issues/718 and https://github.com/uProxy/uproxy/issues/699
* Remove non-uProxy contacts from the uProxy UI
* Clients that are ONLINE_WITH_OTHER_APP are ignored in the core
* User objects with no instances are not sent to the UI
* Removed user.isOnline method in core and property in UI.  Now the core only tells the UI which instances are online (rather than which user).  The UI then uses the existing model.contacts categories to tell whether a user is online (i.e. whether any of their instances are online), so there is no need for a redundant user.isOnline property.
* Now showing which instances are online in the UI (offline instances appear 0.5 opacity) - before this change it was impossible to tell which instances were online for multi-instance …
> Remove non-uproxy contacts, show if specific instances are online

- Gruntfile.coffee
- README.md
Three things I noticed while acting as build cop this morning:
* there's no need for users to install the typescript compiler globally since it's specified as a dependency in our package.json and grunt-ts will find it there
* `bower install` is part of our `npm prepublish` script so there's no need to ask users to run it manually
* `grunt clean` should clear the bower directory (just like it clears `build/`)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/768)
> some fixes to setup instructions and grunt clean

- src/chrome/extension/scripts/chrome_browser_api.ts
This is a work around for an issue in Canary detailed here: https://code.google.com/p/chromium/issues/detail?id=448172&thanks=448172&ts=1421102735
Once Canary behaviour is as expected, we can resolve this issue: https://github.com/uProxy/uproxy/issues/777
ran grunt test.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/778)
> Work around for chrome.proxy.settings.get bug.

- Gruntfile.coffee
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-instance.ts
Fix for #761.  We now create a new rtcToNet_ object for each OFFER (i.e. for each attempt to start proxying).
Tested in grunt test with updated test cases, Chrome.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/786)
> Create a new rtcToNet_ object on each OFFER

- package.json
- src/chrome/app/manifest.json
- src/chrome/extension/manifest.json
- src/mocks/freedom-mocks.ts
Update uProxy package.json and Chrome (app and extension) manifest.json versions to 0.6.0. Moving forward the Chrome webstore versions should be in sync with the newest uProxy release versions (meaning the minor version should be increased every 3 weeks).
Also updated uproxy-lib and freedom dependencies to the latest available packages in npm. (uproxy-networking was already up to date.) In order for tests to pass with updated uproxy-lib, freedom mocks were updated. Note that these should be cleaned up at some point (https://github.com/uProxy/uproxy/issues/838).
Ran grunt test and end-to-end test.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/839)
> Update uProxy, Chrome webstore and dependency versions

- src/chrome/extension/scripts/background.ts
- src/chrome/extension/scripts/chrome_browser_api.ts
- src/chrome/extension/scripts/chrome_core_connector.ts
ran grunt test
If the app is not installed, the popup shows an error prompting the user to install the app. The button in the extension used to always open the Chrome webstore app install page, but with this change, if the user has uproxy.org/chrome-install open, it will activate that tab instead.
This is assuming that uproxy.org is not blocked (which is why it's open).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/811)
> When the app is missing, redirect to uproxy.org when appropriate from within the extension.

- src/generic_ui/polymer/root.html
Status text had an absolute width set which caused a scrollbar to appear
if the window went below a width of ~380px, even without any text
present.  With this change, that scrollbar should no longer appear and
the text will fill the full width (given enough content).
Closes #881 
Tested with standard and unrealistically-long status texts, scrollbar does not appear until the width is at ~180px (seems to be because of the top toolbar which is not responsive at low widths at the moment)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/882)
> Remove width restriction for status text

- src/generic_core/remote-instance.ts
The function does not appear to be used anywhere
Ran grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/922)
> Remove RemoteInstance:updateClientProxyConnection

- .shippable.yml
- .travis.yml
- package.json
Ran grunt test
- Fixes Shippable error (https://github.com/uProxy/uproxy/issues/920)
- Moves "bower install" and "grunt test" out of package.json and into the Travis and Shippable .yml files
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/939)
> Install bower before running Shippable tests

- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/ui.ts
If we (in the case, the UI) receives a message to indicate that we
stopped proxying and we did not know we were proxying, do not show any
notification about that.
This also adds tests both for the fact that the notification will be
generated in a normal case and that the notification will not be
generated in the error case.
Fixes #908 
Tested by ensuring that the first test failed beforehand and now passes
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/944)
> Do not show a notification if a pending shared connection is aborted

- src/generic_ui/polymer/faq-link.html
- src/generic_ui/polymer/link.html
- src/generic_ui/polymer/link.ts
- src/generic_ui/polymer/settings.html
The links in the settings pane can now all be accessed through pushing
the tab keys.  Pushing either enter or spacebar when over those links
will now fire the on-tap handler as well.
This also adds a small highlight to the update and reset buttons when
they are focused since paper-button does not do so by default.
Fixes #929
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/951)
> Add some accessibility features to the settings pane

- src/generic_ui/polymer/copypaste.html
For some reason, the copy paste toolbar was inheriting the styles of the
one in the contact list on the Firefox browser, this renames it and the
issue no longer seems to be present.
Tested by loading the copypaste UI in Firefox and Chrome
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/956)
> Rename the id for the copy paste toolbar

- src/generic_ui/polymer/link.html
This moves the tabindex field for uproxy-link to the span inside of the
polymer element which should cause less content to appear in the
outline when the link is tab-selected
Fixes #972 
Tested by pressing tab in the settings pane.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/974)
> Move the tabindex field for uproxy-link to inner content

- Gruntfile.coffee
- src/chrome/app/install-incomplete.html
- src/chrome/app/polymer/ext-missing.html
- src/chrome/app/polymer/ext-missing.ts
ran grunt test and manually tested to make sure the page changes to index.html upon install.
should be last piece of Chrome install flow, resolving: https://github.com/uProxy/uproxy/issues/627 and https://github.com/uProxy/uproxy/issues/576
looks like this now:
> Match missing extension page to missing app page.

- src/generic_ui/polymer/copypaste.html
- src/generic_ui/scripts/ui.ts
If we encounter any errors with a url (most likely missing characters at
the end) we will now abort trying to process it and instead will show an
error to the user.
Tested by pasting invalid URLs a few times
Fixes #958
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/968)
> When we identify a bad URL, show an error to the user

- src/generic_ui/polymer/root.html
This replaces the toolbar we are using on the roster screen with one
based off of the paper elements.  This allows us to fluidly place
elements instead of worrying about absolute positions as well as to get
nice consistent paper effects.
Tested by clicking around in the UI
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/994)
> Replace the custom toolbar on the roster screen with a paper version

- src/chrome/extension/scripts/chrome_browser_api.ts
Fixes https://github.com/uProxy/uproxy/issues/936
Manually tested in 40.0.2214.115 (the only channel where we seem to get this issue)
Also ran grunt test.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/985)
> Check chrome.runtime.lastError

- src/generic_ui/polymer/root.html
This (hopefully) fixes the UI issue of the ink effect appearing to be
too jarring on the navigation tabs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1013)
> Add transparency to the paper-tab ink effect

- src/generic_core/consent.ts
- src/generic_core/core.ts
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-instance.ts
- src/generic_core/social.spec.ts
- src/generic_core/social.ts
- src/generic_core/user.spec.ts
- src/generic_core/user.ts
- src/generic_ui/polymer/network.html
- src/generic_ui/polymer/settings.ts
- src/generic_ui/polymer/splash.html
- src/interfaces/network.d.ts
* Remove _ fields from consent messages/storage: https://github.com/uProxy/uproxy/issues/871
* better message logging and cleanup of send method (now only Network has a send method which handles logging, rather than additional methods in User and RemoteInstance): https://github.com/uProxy/uproxy/issues/1001
* small UI cleanup to splash screen (more padding around "Set up a one time connection"), now looks like:
Tested in Chrome, new grunt test (found https://github.com/uProxy/uproxy/issues/1011)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1012)
> Remove _ fields from consent messages/storage, better message logging, small UI cleanup to splash screen

- src/generic_core/consent.ts
- src/generic_core/remote-instance.ts
Fixes #1025 and provides a better fix for #871.
Tested in "grunt test" and Chrome
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1026)
> Remove private Consent.State fields so we no longer need serialize

- Gruntfile.coffee
- src/generic_core/consent.spec.ts
- src/generic_core/consent.ts
- src/generic_core/core.spec.ts
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-instance.ts
- src/generic_core/user.ts
- src/generic_ui/polymer/instance.ts
- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/user.spec.ts
- src/generic_ui/scripts/user.ts
- src/interfaces/instance.d.ts
- src/interfaces/ui.d.ts
- src/uproxy.ts
This removes the consent.js file from the UI build by adding a new
interface, ConsentState, and using that on the UI side instead of trying
to create actual consent objects.  It also moves the WireState interface
and UserAction enum to uProxy.
This creates the interface uProxy.ConsentState, switches the consent
field in the UI.Instance to be of type uProxy.ConsentState, and removes
some code duplication in tests (while moving them away from using
Consent.State
WireState and UserAction, both also shared state, have also been moved
to uproxy.ts
Tested through grunt test and by running in Chrome
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1031)
> remove core/consent.js from UI build

- src/generic_core/consent.ts
- src/generic_core/core.spec.ts
- src/generic_core/core.ts
- src/generic_core/firewall.ts
- src/generic_core/local-instance.ts
- src/generic_core/remote-connection.ts
- src/generic_core/remote-instance.ts
- src/generic_core/social.spec.ts
- src/generic_core/social.ts
- src/generic_core/storage.ts
- src/generic_core/user.spec.ts
- src/generic_core/user.ts
- src/generic_ui/polymer/network.ts
This takes care of moving us away from using console.log throughout
generic_core and instead uses the freedom logger.  At the same time,
this also includes a number of general cleanups to logging and error
handling.
General principles of logging used in the restructure:
* Messages should be greppable.  If I see a message in the console, I
should be able to grep it in the code and figure out where it is
coming from.  Obviously there may be extra variable data at the end of
the mesasage, but it should be clear what that is
* The same message should not be logged twice.  There are some
exceptions with this due to the nature of passing messages between the
app and the extension, however, in general, we will try not to log
something too many times (e.g. log the data right before calling the …
> Switch to using the freedom logger

- package.json
The API changed in the major version bump is not used by the uProxy UI. Just want to keep ye up to date.
Tested locally by proxying between Dexter and Bob.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1043)
> stick with latest version of uproxy-networking

- src/generic_ui/polymer/copypaste.html
- src/generic_ui/polymer/copypaste.ts
When the user clicks on the textarea containing the copy-paste url, we
will immediately select the entire url
Tested by clicking on the url
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1040)
> Handle selecting copypaste urls better

- src/generic_ui/polymer/tip.html
This uses float: right for the tooltip close button instead of setting
an absolute position.  It should have no real effect on the actual
display unless the content would intersect with the close button
previously.
Tested by experimenting in UI
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1062)
> Reposition the close button for uproxy-tip, update comment

- src/firefox/data/scripts/firefox_browser_api.ts
- src/firefox/lib/glue.js
Some minor plumbing to get faq links to open in firefox. should be able to roll forward to act as the more generic openURL that will appear per https://github.com/uProxy/uproxy/pull/1059
fixes #647
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1066)
> FAQ opens in firefox

- src/chrome/extension/manifest.json
Fixes #679
Tested in Chrome
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1069)
> Remove content_security_policy from Chrome extension (use default)

- src/chrome/extension/manifest.json
The copypaste.html not being in the web_accessible_resources array for
the chrome extension manifest was causing redirects to it through the
Google proxy to fail to load.  This caused clicking on the link from in
a hangout message to just endlessly load.
Fixes #1065 
Tested by clicking on a copy+paste link from hangouts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1070)
> Add copypaste.html to web_accessible_resources

- src/generic_ui/polymer/tip.ts
This improves the detection of hidden elements by using
window.getComputedStyle to check whether the current or target element
are currently hidden.  This works in many more cases than the previous
hacky checking of positions.
This also will treat the target element as occupying the full possible
width if there is no parent element (e.g. the previous element is a
top-level component in a web component.
This just fixes more issues that came up while working on copy+paste errors.  Tested by looking at the error messages.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1072)
> Improve detection of hidden elements for uproxy-tip

- src/chrome/extension/scripts/chrome_core_connector.ts
Set ui.view to SPLASH when app is connected.  This was removed in https://github.com/uProxy/uproxy/pull/1056 but is needed to properly advance to the SPLASH screen if you first install the chrome extension then the app.
Tested in Chrome
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1081)
> Set ui.view to SPLASH when app is connected

- src/generic_ui/polymer/root.ts
The code was originally added here https://github.com/uProxy/uproxy/pull/971 because Polymer used to error when I tried this before. Seems to be working now without using the extra div.
Addressing this: https://github.com/uProxy/uproxy/issues/1091 
This was the only place in uproxy/src setting innerHTML
ran grunt test and tested manually (made sure the 'application missing' page showed up when it should)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1099)
> Add new Polymer element without setting innerHTML.

- Gruntfile.coffee
- src/chrome/extension/copypaste.html
- src/chrome/extension/scripts/background.ts
- src/chrome/extension/scripts/copypaste.ts
- src/firefox/lib/url-handler.js
- src/generic_ui/scripts/ui.ts
This fixes an issues where the uProxy popup would, in Chrome, not
actually be at the front by the end of the page redirect.  This seems to
be due to the main window regaining focus when the tab loads.
To get around this, we register a callback from that tab to send a
message to the extension telling it to bring the uProxy window to the
front.  This message is handled in the background script for the
extension.
This also moves the responsibility of launching the window out of
generic_ui and into the browser-specific code.
Fixes #1064
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1078)
> Make sure uproxy tab stays in front with URL pasting

- src/firefox/lib/firefox_proxy_config.js
This makes sure that we set the correct fields when configuring the
Firefox proxy and makes sure we reset the correct fields when proxying
ends
Fixes #1120
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1121)
> Changes to setting/resetting Firefox proxy settings

- src/generic_ui/polymer/confirm.ts
- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/contact.ts
- src/generic_ui/polymer/instance.html
- src/generic_ui/polymer/instance.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/roster.html
- src/generic_ui/polymer/roster.ts
- src/generic_ui/scripts/ui.ts
I approximately halved the space under Computer 1, 2:
Let me know if you want to keep the tooltip:
Also renamed the "other" group:
addressing:
https://github.com/uProxy/uproxy/issues/1127
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1128)
> Update roster titles, fix instance margin, sharing access tooltip.

- src/firefox/lib/glue.js
- src/firefox/lib/main.js
- src/firefox/lib/url-handler.js
Fix the label for the uProxy button in the Firefox UI to just read
"uProxy" instead of "uProxy-button"
The Firefox panel now opens up attached to the button in all cases, not
just for the initial appearance.
Fixes #1092
Tested by forcing opens of the Firefox dialog and checking they are attached to the button as well as opening up the customize menu in Firefox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1134)
> Fix Firefox button label, panel position

- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/splash.html
This removes our hiding of webkit scrollbars in the universal case and
re-enables hiding of cross-browser scrollbars in the case where they are
not needed.
Fixes #1135
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1142)
> Show scrollbars whenever scrolling is available

- src/chrome/extension/manifest.json
Addressing this: https://github.com/uProxy/uproxy/issues/1136
Upon install, don't show the error icon. However, if the app disconnects after being connected for some time, the error icon will still appear (this is existing behaviour). In that case, we should give better error recovery instructions though; bug here: https://github.com/uProxy/uproxy/issues/1148.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1149)
> Set default browser icon to offline icon.

- src/firefox/package.json
The unsafe-content-script permission is no longer needed in Firefox,
remove it from the manifest.
Fixes #680
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1146)
> Remove the unsafe-content-script permission from Firefox

- bower.json
- src/generic_ui/polymer/description.html
- src/generic_ui/polymer/description.ts
- src/generic_ui/polymer/feedback.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/polymer/settings.html
- src/uproxy.ts
Tested manually and grunt test.
- Resolve this issue: https://github.com/uProxy/uproxy/issues/1150
- Before, if the window is too narrow, you can't close the settings panel. Now you can close it by swiping the right edge of the panel. 
- Remove the SETTINGS view. Settings is now part of the roster view.
- Update styling:
The only weirdness is opening the advanced settings in the default window size:
Log out is pretty close to the bottom :( although the panel is now scrollable so you could get this:
@zahoriea would you prefer to shrink things so that it fits nicely? or did we want to keep an issue to move advanced settings to its own full panel, which would resolve this?
A lot of this CL was fixing tabs and moving things into new divs, if someone wants to walk through the code together …
> Fix bugs with settings panel.

- src/generic_core/core.ts
- src/generic_core/diagnose.ts
- src/generic_core/freedom-module.json
- src/generic_core/messages.ts
- src/generic_ui/polymer/feedback.html
- src/generic_ui/polymer/feedback.ts
- src/generic_ui/polymer/logs.html
- src/generic_ui/polymer/logs.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/view-logs.html
- src/uproxy.ts
Checking the checkbox opens this dialog:
Clicking More Info takes you to the "does uproxy log data about me" question in the FAQ.
I updated the hover text:
Clicking "Preview" opens this:
Clicking "No" just sends you back to the feedback page, more info goes to FAQ and yes will open the new view logs page (below):
View logs page, while loading:
View logs page, loaded, with NAT data at the top:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1173)
> Add NAT to logs. Show in new view-logs page.

- src/generic_ui/polymer/app-bar.html
- src/generic_ui/polymer/copypaste.html
This fixes two issues with the app bar on the copy+paste page
First of all, there were some cases where two headings were displayed at
the same time, this removes that.
Second, this removes text wrapping from the app-bar heading.
Fixes #1183
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1188)
> Fix issues with copy+paste app bar

- src/generic_core/core.ts
- src/generic_core/diagnose.ts
- src/generic_ui/polymer/feedback.html
- src/generic_ui/polymer/feedback.ts
- src/generic_ui/polymer/instance.ts
- src/generic_ui/polymer/logs.html
- src/generic_ui/polymer/logs.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/splash.html
- src/generic_ui/polymer/troubleshoot.html
- src/generic_ui/polymer/troubleshoot.ts
- src/generic_ui/scripts/core_connector.ts
- src/uproxy.ts
To do in this pull request:
- Add 'X' button to close Unable to Proxy dialog (or add 'Try Again' option beside the 'Analyze Network' button)
- Add padding on top of 'Submit Feedback' on the Splash page
- Make the checkbox label on the feedback page link to the View Logs page, and remove the pop-out icon that currently opens that page
- Add a timeout to getNatType when feedback is being sent -- if it takes longer than 30s (?) we will submit all feedback except the NAT type. This will guarantee that the 'Submitting Feedback' dialog will be closed.
To do in future pull request: the new uproxy-troubleshoot element should be added to the Advanced Settings page when that is created (the contents of uproxy-troubleshoot should be taken out of the paper-dialog and added to a core-overlay)
[<img …
> Fallback if Feedback submission fails. Help user classify NAT if proxying fails.

- src/generic_ui/polymer/troubleshoot.html
- src/generic_ui/polymer/troubleshoot.ts
Paper-action-dialogs were not opening when the corresponding core-signal was fired. Changing to paper-dialog fixed this.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1193)
> Change dialog type to allow it to open on core-signal.

- src/generic_ui/polymer/instance.ts
I thought this was the fix: https://github.com/uProxy/uproxy/pull/1193
I originally tested by firing a core-signal, but I didn't realize that firing from inside a promise then() or catch() block doesn't work. I tested this by trying a proxy I knew would fail. Should be working correctly now.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1200)
> Fix to open troubleshoot dialog when proxying fails.

- src/generic_ui/polymer/roster.html
This replaces the no-contacts image on the main roster page (it was
using the default contact image we have) with the person core icon.
Fixes #1168
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1197)
> Replace the no-contacts image on the main roster page

- src/chrome/app/scripts/background.ts
- src/generic_core/core.ts
- src/mocks/freedom-mocks.ts
The type errors we are seeing when we build actually turn out to be
because freedom should not be called with the new operator, this removes
that.
Initially, we never touch the return value from calling it in
`chrome/app/background.ts`, so don't bother saving it in a variable.
This also fixes the description of freedom in our mock.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1205)
> Remove the type errors we see every time we build

- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
Previously, we had a polymer watcher on model.globalSettings.mode which
would trigger `modeChange` which would update the globalSettings state
in core whenever mode was changed.  This caused `updateGlobalSettings`
to be called multiple times in some cases (except for the two instances
in `root.ts` that relied on the watcher, all other cases still
explicitly updated settings themselves) and resulted in it being called
in error at other points (initialization caused it to be called, even if
globalSettings itself was not fully populated).
We now manually call `updateGlobalSettings` when the user clicks the get
or share tabs.
Fixes #1190
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1201)
> Explicitly update global settings when changing mode

- src/generic_ui/polymer/settings.html
Even if we are sent a non-square profile picture, we should be sure not
to stretch the image.  This provides a temporary fix for
freedom-firebase sending down non-square facebook profile pictures and a
general fix to make sure that images will never be distorted horribly.
Fixes #1171
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1195)
> The profile picture in settings should never be stretched

- src/generic_core/core.ts
This separates the functionality for sending a post request from sending
the feedback-specific data and adds alternate urls to retry for the
feedback
Fixes #1191
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1215)
> Add the ability to send feedback to alternate (hardcoded) urls

- src/generic_ui/polymer/instance.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
When a user attempts to proxy with an offline instance, do not attempt
to connect to that instance.  Instead, we now display a toast
notification reminding the user that their friend is offline.
This also adds the ability to display a toast notification
Fixes #1224
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1231)
> Do not attempt to proxy with an offline instance

- src/generic_ui/index.html
- src/generic_ui/polymer/splash.html
Use Quicksand font for uProxy splash page, to match website, FAQ, etc
Screenshot:
Tested on Chrome and Firefox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1236)
> Use Quicksand font for uProxy splash page

- src/generic_core/core.ts
- src/generic_core/remote-instance.ts
The previous behaviour we had when attempting to start a new connection
was that we would try to terminate any existing connection and would
immediately start trying to connect.  This sometimes caused a race
condition when the state was not completely cleaned up.
To get around that issue, we now wait for the old connections to finish
cleaning up before we try to start a new one.
Fixes #1234
Tested by manually switching who I am proxying with multiple times without clicking stop.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1237)
> core: Wait to clean up old connection before starting a new one

- src/generic_ui/polymer/settings.html
This updates the styling for the user image in settings to be cover,
that should look a bit better for cases where the picture is extra-wide.
Still waiting on getting back user-decided pictures to make this a solid
fix.
This will center the picture which may be undesirable in some cases, any
other positioning also has that possibility though.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1243)
> Switch styling for user image in settings to cover

- Gruntfile.coffee
Chrome apps and chrome extensions cannot be loaded if there are files starting with '_'. This pull request renames the output files for SpecRunners to just be named 'SpecRunner.html' so that or a development build, if the SpecRunners are in the location of the extension or app, this doesn't require their manual removal. 
(see https://github.com/uProxy/uproxy/issues/474)
TESTED: 
grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1235)
> Name Specfiles SpecRunner.html to avoid breaking app/extension loading

- src/generic_core/core.ts
This removes the most dangerous (and easily-identified) PII from the
logs: emails and pictures.
For emails, we will replace any email address found with EMAIL_{ID}
where ID a numeric ID that will be consistent throughout that single
log.  The original proposal was to use a salted hash with a salt known
only to the reporter, however, that would end up being more difficult to
implement, less performant, and it would offer us a stronger chance of
determining what an email address was based on the logs.
For any base64-encoded image data we detect in the logs, we will replace
it with "IMAGE_DATA".  I cannot imagine any cases where the actual
content of an image would be useful in debugging.
Fixes #1164 …
> Remove some PII from the logs

- src/generic_ui/polymer/copypaste.ts
- src/generic_ui/scripts/ui.ts
Currently, if a user gets disconnected and then tries to reconnect, we
will not clear any old proxying settings on the browser before trying to
set the new ones.  On Chrome, this results in new settings not getting
set and us getting stuck in a state where we are not proxying.
Fixes #1238
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1251)
> Clear old endpoints before setting a new one

- bower.json
- src/generic_core/remote-connection.ts
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-instance.ts
- src/generic_ui/polymer/copypaste.html
- src/generic_ui/polymer/instance.ts
- src/generic_ui/polymer/link.html
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/polymer/troubleshoot.html
- src/generic_ui/polymer/troubleshoot.ts
- src/generic_ui/scripts/ui.ts
- src/uproxy.ts
Fixes: https://github.com/uProxy/uproxy/issues/1203
Toasts now float appropriately relative to getting/status bars, e.g.
No statuses:
One status:
If width is <320px the toast sticks to the sides:
I can take this out if it looks weird.
Updated error flow
If getting fails:
Clicking No or the X will dismiss the dialog. Clicking Yes opens:
Clicking Yes opens feedback, with the logs option pre-checked:
Please let me know how copy/style can be improved!
Right now the question icon, "More info" and "Privacy policy" all link to the FAQ about logs. @gwpenn is writing up new content!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1246)
> Show troubleshoot dialog on sharer's side. Keep error flow within popup dialog.

- src/generic_core/social.spec.ts
- src/generic_core/social.ts
We believe this monitoring doesn't really give us much, We should have instances for all clientIds that are ONLINE. ONLINE means user is online with uproxy.
But for some weird case that we saw from user log I see that uproxy keeps sending instance_request for some client ids. These are all jabber... user ids.
I believe user is not really online with uproxy, but for some reason social provider gives us ONLINE, We'd like to investigate this, but for now to avoid xmpp throttling us we'll increase the monitoring interval to 1 minute.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1244)
> change monitoring interval from 5s to 1 minute

- README.md
- package.json
This takes a step out of the initial build process by running bower
install immediately after finishing npm install.
Tested by running npm install with a clean repository.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1198)
> Run bower install as part of npm install

- src/generic_core/remote-connection.ts
- src/generic_core/remote-instance.spec.ts
- src/mocks/socks-to-rtc.ts
Temporary fix for https://github.com/uProxy/uproxy/issues/1264
Currently on Firefox, the socksToRtc 'stopped' event never fires, due to some issues closing TCP sockets.  uProxy core doesn't actually care that these sockets haven't been closed, and we need to know the proxying is stopped so that we can properly clean up (remove browser socks5 proxy settings).  We can do this by connecting to the 'onceStopping_' promise, which is fulfilled as soon as stopping begins, instead of the 'stopped' callback which only gets called when all sockets have been closed (which never happens in FF).
Long term fix for this is to fix underlying uproxy-networking / socket issues in Firefox.
Tested in Chrome (no change), Firefox, updated grunt test
[<img src="https://reviewable.io/review_button.png" height=40 …
> Use socksToRtc onceStopping_ rather than stopped to get around Firefox stop-proxying bug

- src/generic_core/core.ts
Remove url and imageData from logs
Before:
```
{"userId":"100006963823986","lastUpdated":1429297992786,"name":"NAME_1","url":"https://www.facebook.com/profile.php?id=100006963823986","imageData":"https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfa1/v/t1.0-1/p100x100/10487395_1411734449068669_3657311256448408178_n.jpg?oh=83937bad852014fb7ef2be4d4afb8164&oe=55D62430&__gda__=1436094844_4462a8cf349f4d8de49587fccc877a9f"}
```
After:
```
Received own XMPP profile {"userId":"6706848","lastUpdated":1429297950079,"name":"NAME_1","url":"URL","imageData":"IMAGE_DATA"}
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1301)
> Remove url and imageData from logs

- src/firefox/lib/glue.js
- src/generic_core/freedom-module.json
This moves the Firefox content proxy from never being included to being
included on every local page.
Yeah, this is embarrassing.
Tested by opening the logs page
Fixes #1329
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1331)
> Fix the target page for firefox content proxy

- src/generic_core/diagnose-nat.ts
- src/generic_core/globals.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/settings.ts
Due to an upstream bug (willscott/webrtc-adapter#5), we are unable to
specify multiple urls for a single stun server.  To get around this, we
now specify each URL individually.
At the same time, this removes the many different locations where we
have constants for the stun servers; that is now only done in
globals.ts.
Fixes #1332
Fixes #1326
Tested by starting a copy+paste connection as well as viewing network info/logs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1349)
> Stop specifying multiple urls per stun server

- src/chrome/extension/scripts/background.ts
- src/chrome/extension/scripts/chrome_core_connector.ts
- src/firefox/data/scripts/firefox_connector.ts
- src/generic_ui/scripts/core_connector.ts
- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/browser_connector.ts
The chrome core connector previously required access to the ui object in
order to change state when disconnect or connect events occurred.  This
modifies the functionality of the core connector so that it will trigger
an event when those events occur.
For firefox, we add a connect function that does nothing except for
triggering the event.
Tested by opening chrome with and without the app installed (and installing the app after opening chrome)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1323)
> Remove the dependency between chrome_core_connector and ui

- src/generic_core/freedom-module.ts
- src/generic_core/uproxy_core.ts
TESTED: 
* grunt
* Loaded uProxy, and ran: 
```
var logging_types = browserified_exports.logging_types;
var loggingController = browserified_exports.loggingController;
loggingController.setDefaultFilter(
logging_types.Destination.console,
logging_types.Level.debug);
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1368)
> Allow access to logging controller

- src/generic_ui/polymer/action-dialog.html
- src/generic_ui/polymer/action-dialog.ts
- src/generic_ui/polymer/feedback.html
- src/generic_ui/polymer/root.html
This creates uproxy-action-dialog, a minor extension of
paper-action-dialog.  paper-action-dialog has the possibility of setting
the left and top positions of an element to be <0 which has the
obnoxious side-effect of ruining later calculations of what the width of
an element should be (and which then has the possibility of ruining
later calculations of what the position of the elemnt should be).
uproxy-action-dialog checks that the position set is always on-screen
and corrects that if not.
Fixes #1361 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1373)
> Create and use uproxy-action-dialog

- src/generic_core/freedom-module.ts
TESTED: 
* grunt 
* loaded into the browser context and tried to examined socks_rtc and rtc_net from browserified_exports.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1372)
> export socks_rtc and rtc_net for easier & deeper debugging

- src/generic_ui/polymer/feedback.html
- src/generic_ui/polymer/settings.html
Fixes this: https://github.com/uProxy/uproxy/issues/1357
Tested manually + grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1376)
> Tune metrics checkbox styling. Fix autogrow feedback box in Firefox.

- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/ui.ts
Disable sharing for Firefox 37 and later, due to https://github.com/uProxy/uproxy/issues/1360
Unforunately we are reusing the polymer paper-dialog, where we can use any links, so we are showing a goo.gl URL rather than do something clickable.
Tested in Chrome (no difference) and Firefox version 37
@lucyhe Can you test in Firefox 36 and verify this doesn't disable sharing?  Sorry I don't have that version
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1390)
> Disable sharing for Firefox 37 and later

- src/generic_ui/polymer/root.ts
Without this, if the user closes the popup when the stats dialog is open, when they reopen the popup (in Chrome), the dialog will be gone.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1374)
> Reopen stats dialog when root element is ready, if needed.

- src/generic_ui/polymer/root.html
- src/generic_ui/scripts/user.ts
Contacts will now expand when an offer or request is received and there previously were no offers or requests for that contact. (However, regardless of offers, a contact will not auto-expand if the user is ignoring that contact.)
Tested manually and ran grunt test.
Chrome
Larger numbers:
Firefox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1405)
> Add notification numbers to get/share tabs. Expand contacts for new offers.

- package.json
freedom-social-firebase 0.0.11 had a bad build (firebase.js was missing, causing Facebook to be completely broken).  0.0.12 fixes this (includes firebase.js in the dist/ directory)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1428)
> Update freedom-social-firebase version

- src/generic_ui/polymer/dialog.ts
The previous fix for dialogs handled the case where we would attempt to
position the dialog to be off the screen which would cause later
calculations for its width to be completely wrong (keeping it off the
screen).  There was another problem we did not notice at the time: that
the second calculation for its position in Firefox would ocasionally
occur before we had any information on what its width would be, set it
to be placed in the middle of the screen, which would end up forcing it
to be offscreen.
Fixes #1361 (again)
Testing
-------
0. Add a logging statement to `repositionTarget` in `dialog.ts`
0. Keep restarting Firefox with logs going somewhere you can read them until that log statement shows up on two consecutive lines (this is the case where the UI did not have a chance to …
> Try to fix the case where dialogs open too far to the right

- src/chrome/extension/scripts/background.ts
We were previously launching the extension window whenever Chrome or the
extension were updated, this changes the behaviour so that it only
happens the first time the extension is installed.
See https://developer.chrome.com/extensions/runtime#event-onInstalled
Fixes #1364
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1439)
> Only launch the extension window on initial install

- Gruntfile.coffee
- src/generic_ui/disconnected.html
- src/generic_ui/polymer/confirm.html
- src/generic_ui/polymer/copypaste.ts
- src/generic_ui/polymer/instance.ts
- src/generic_ui/polymer/network.ts
- src/generic_ui/polymer/root.ts
- src/generic_ui/polymer/settings.ts
- src/generic_ui/polymer/splash.ts
- src/generic_ui/view-logs.html
Sets file-level globals like ```var ui = ui_context.ui``` in various Polymer .ts files, so that we can turn long lines like ```ui_context.ui.startGettingInUiAndConfig(null, ui_context.ui.copyPastePendingEndpoint);``` into more readable code like ```ui.startGettingInUiAndConfig(null, ui.copyPastePendingEndpoint);```
This pull request also creates separate vulcanized Polymer files for disconnected.html and view-logs.html.  Before those had been using the same vulcanized.html as our main index.html UI, which meant they were pulling in unnecessary Polymer elements like the roster, copypaste, etc, and were also getting exceptions because ui_context is not available in those environments.
Tested in Chrome and Firefox (main UI, disconnected.html, faq.html, view-logs.html, extension missing page) …
> Remove excess "ui_context." in Polymer .ts files.  Clean up vulcanize rules in Gruntfile

- third_party/tsd.json
We have the really annoying dependency rule that we need to pull in
typings for any child repo since the files get copied to our third_party
directory instead of living in their build directories that have the
typings specified.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1448)
> Add a DefinitelyTyped rule for circular-json

- README.md
[NPM is not an acronym](https://docs.npmjs.com/misc/faq#is-it-npm-or-npm-or-npm) for "Node Package Manager." Also, "manager" doesn't have 3 "a"s.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1450)
> NPM is not an acronym

- src/generic_ui/polymer/settings.html
This changes the settings text to something that is not so ridiculously
large and removes our manual override on the font size for the labe.
Fixes #1412
Fixes #1419
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1447)
> Change settings text, remove sizing override

- package.json
uProxy becomes unusable with freedom-for-firefoxv0.6.11, this changes
the version we require to v0.6.10.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1464)
> Downgrade freedom-for-firefox

- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/contact.ts
- src/generic_ui/polymer/instance.ts
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/ui.ts
Move the functionality to start a proxying session to UserInterface
Starting a connection through a given user is an action that is being
taken place on the level of the entire UI, not specific to a single
instance.  This moves the functionality to actually do that out of the
instance code to the top-level.  By doing this, we are able to get
better checking of whether there was a problem connecting or whether a
user aborted the connection.
To keep track of the current status of our connection, we now use a
variable in the UI that is set to whatever instance we are trying to get
access through.
Fixes #1409
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1462)
> Move the functionality to start a proxying session to UserInterface

- src/generic_ui/polymer/description.html
In the settings menu, clicking on the description will allow you to edit
it, in addition to clicking on the edit icon to the right.
Additionally, hovering will now correctly show the cursor as a pointer.
Fixes #1269 
Tested by clicking on the text
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1497)
> Allow clicking on the description to edit the description

- src/firefox/lib/glue.js
When we set the uProxy icon for Firefox, update the global icon state
across windows instead of trying to limit the change to a single window
Fixes #1292
Tested by logging in in Firefox and making sure the icon updates across windows.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1494)
> Update global Firefox icon instead of per-window state

- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
The previous way we were handling toast messages was to have a flag
(actually the output of a function) that would change depending on
whether the message should be open or not.  This disable the normal ways
of clearing a toast message (e.g. clicking somewhere else or swiping it
offscreen).
We now watch for changes of ui.toastMessage and will fire the open event
when that changes.
Fixes #1333
Tested by getting failures and making sure the message showed up and subsequently went away.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1498)
> Open toast message with an event

- src/generic_ui/polymer/feedback.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
If the statuses at the bottom of the screen are not visible at some
point, we should factor that into the calculation of how tall they are.
In order to do that, we now accept a boolean value into topOfStatuses
that denotes whether or not they can be seen.  If this value is false,
we just use the padding value for the height of the statuses.
In order to check whether they are visible, we also need to figure out
whether or not the feedback window is open (they cannot be seen if it is
open).  To do this, we have it export the attribute opened which is
calculated based off of whether its internal panel is open.
Fixes #1334 
Pictures from testing below:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1501)
> Factor whether statuses are visible into height calculation

- bower.json
This is a workaround for a bug in the current polymer dependencies that has inconsistent dependencies on "webcomponentsjs".
It also uses standard and consistent version dependency specifications. 
TESTED: 
./setup install
grunt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1514)
> add fix for polymer/webcomponentsjs version bug

- src/generic_core/local-instance.ts
- src/generic_core/remote-user.spec.ts
- src/generic_core/remote-user.ts
- src/interfaces/social.ts
Fix for https://github.com/uProxy/uproxy/issues/1510 (also consolidated issues #1469, #1485, #1314).
We now send the user's name and userId along with the instance handshake.
* If a peer receives a handshake from a user whose name is still 'pending' (one who they haven't got a UserProfile for), the remoteUser.name will be set to the name sent along with that instance handshake
* Sometimes a user doesn't even know their own name (they haven't received their own UserProfile, due to GTalk XMPP weirdness).  In this case peer's can use their userId as a name.  This userId should be their real user ID (e.g. their GMail address), and not some anonymized @public.talk.google.com ID.  This will result in their email address appearing in the uProxy UI which isn't great but is much better than the …
> Send name and userId along with the instance handshake

- src/generic_ui/polymer/root.html
This starts treating the welcome bubble as part of the header for the
core-header-panel.
For the position of bubbles, we try to do the computation based on the
height of the previous element and its position (prev.height + prev.top
should give us the top amount that we want to use).  This works usually,
but we were running into a problem where the calculation would be done
based on the core-toolbar but the actual positioning would be done based
on a separate div that was placed below core-toolbar due to the selector
in core-header-panel.
In order to fix this, we have added the class core-header to the bubble
which causes it to be filled into the same div in core-header-panel as
the toolbar itself.
Fixes #1523 …
> Treat welcome bubble as part of header

- src/generic_core/remote-user.ts
- src/generic_core/social.ts
- src/interfaces/social.ts
Show Facebook contacts without any known instances.  For Facebook (unlike Google), we know that every contact who we get a UserProfile for must have permissioned uProxy (Facebook's <user>/friends endpoint only returns friends who have granted that app OAuth permission).
This solves the problem where Alice and Bob are both Facebook friends, yet the first time Alice signs into uProxy w/ Facebook Bob is not online, and vice-versa, and they don't appear in each others buddy list.
Tested on Chrome, Firefox, reran "grunt test"
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1540)
> Show Facebook contacts without any known instances

- Gruntfile.coffee
- src/generic_ui/index.html
- src/generic_ui/polymer/app-bar.html
- src/generic_ui/polymer/bubble.html
- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/copypaste.html
- src/generic_ui/polymer/description.html
- src/generic_ui/polymer/feedback.html
- src/generic_ui/polymer/instance.html
- src/generic_ui/polymer/network.html
- src/generic_ui/polymer/reconnect.html
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/roster.html
- src/generic_ui/polymer/settings.html
- src/generic_ui/polymer/splash.html
- src/generic_ui/polymer/troubleshoot.html
- src/generic_ui/style/global.css
This works towards the goal of getting rid of some of our absolutely
dreadful CSS duplication.  Styles that we find ourselves repeatedly
applying everywhere we use some elements should be contained in the same
place, and we should also be trying to do things with as few rules as
possible (e.g. let's pick a default font size and change it, at the
highest level possible, only where it needs to be changed).
This obviously does not address most of our problems, however, it does
create a single file at the global scope that handles colouring
paper-buttons teal (or grey) as well as well as changing the colouring
for the progress bars we use.
Works towards the conveniently opened #1542 …
> Add some global css rules

- src/generic_core/consent.ts
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-user.spec.ts
- src/generic_core/remote-user.ts
- src/generic_core/social.spec.ts
- src/generic_core/social.ts
- src/generic_core/uproxy_core.spec.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/user.spec.ts
- src/generic_ui/scripts/user.ts
Fixes https://github.com/uProxy/uproxy/issues/688
We now allow proxying through other instances of yourself, which works in both Google and Facebook.
Some additional changes:
* Other instances of yourself are automatically permissioned for access
* We don't display you as a user in the buddylist unless you have another instance (i.e. multiple instances).  This is to prevent brand new users from signing in with Facebook and just seeing themselves on the buddylist
* We don't display desktop notifications for permission changes for other instances of yourself (to prevent "X has granted you access" from automatically appearing as soon as you sign on in 2 places with the same user)
* We only show the sharing enabled icon and tooltip if you are sharing with someone other than yourself
* Removed …
> Enable proxying through yourself

- src/chrome/extension/scripts/chrome_browser_api.ts
- src/firefox/data/scripts/firefox_browser_api.ts
- src/generic_ui/polymer/instance.html
- src/generic_ui/polymer/proxy-error.html
- src/generic_ui/polymer/proxy-error.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/browser_api.ts
This fixes errors in Chrome where we would be unable to proxy but would still tell the user that we were proxying.  With this change, we will not allow the user to set a proxying session when we are unable to actually control the settings.  Additionally, if the browser stops sending traffic through a proxy session, we will display an error.
Check commit messages for more details.
Tested by manual evaluation of the UI while toggling another extension that had precedence with proxy settings (and had them set).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1562)
> Detect and report when we are unable to proxy

- .gitignore
- Gruntfile.coffee
- src/chrome/extension/polymer/app-missing.ts
- src/chrome/extension/scripts/background.ts
- src/chrome/extension/scripts/context.ts
- src/firefox/data/scripts/background.ts
- src/firefox/data/scripts/firefox_connector.ts
- src/generic_ui/index.html
- src/generic_ui/polymer/context.d.ts
- src/interfaces/browser_connector.ts
We need to browserify context.js from chrome/extension/scripts, otherwise relative paths are wrong.
We copy all polymer files with all the supporting files to chrome/extension directory and vulcanized it from there. This is necessary because we have some browser specific polymer code. So currently vulcanized code lives in chrome/extension/generic_ui/polymer, and it has dependency on context.js, when we try to browserify vulcanized file it breaks again, because paths are wrong.
Possible solutions to this problem are:
1. we don't need to have browser specific elements instead polymer code can live in generic_ui/polymer and bi-browser, similarly the way we do about restart button. That way we could vulcanize polymer code from the common place and copy it to browser specific location. In …
> browserify context.js from chrome/extension/scripts instead of chrome/extension/generic_ui/scripts

- Gruntfile.coffee
- bower.json
https://github.com/webcomponents/webcomponentsjs released version 0.6.2 a few days ago, which breaks our Firefox UI. This updates our dependency to exactly version 0.6.1.
The changes to the Gruntfile fix the view-logs page in Firefox.
Tested manually in Chrome and Firefox.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1584)
> Use webcomponents.js v0.6.1. Update grunt file to copy FF scripts to correct places.

- src/generic_ui/polymer/settings.html
The "Restart" option was showing up in Firefox settings and clicking it wasn't doing anything.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1586)
> Remove 'Restart' option from Firefox settings.

- package.json
- src/generic_core/dev_build/freedom-module.json
- src/generic_core/dist_build/freedom-module.json
- src/generic_core/globals.ts
- src/generic_core/remote-connection.spec.ts
- src/generic_core/remote-connection.ts
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-instance.ts
- src/generic_core/remote-user.spec.ts
- src/generic_core/remote-user.ts
- src/generic_core/social.spec.ts
- src/generic_core/social.ts
- src/generic_core/uproxy_core.spec.ts
- src/generic_core/uproxy_core.ts
- src/interfaces/social.ts
- src/mocks/freedom-mocks.ts
- src/mocks/rtc-to-net.ts
- src/mocks/socks-to-rtc.ts
This moves to uproxy-lib v27's `BridgingPeerConnection` which provides support for negotiating obfuscated peerconnections. This is backwards compatible *except for one-time connections*: If we know a client is running with `MESSAGE_VERSION` 2, initiate an obfuscated connection; for older clients, same as today.
There's one outstanding thing missing from churn: support for generating a random key for each connection. I will work on that, it shouldn't change this pull request.
Tested on Chrome with the Google+ social provider and one-time connections.
Question: I had to re-order the STUN servers in order to make churn work from my internal network...should we bump the `STORAGE_VERSION` too? …
> migrate to uproxy-lib v27, use the bridge (without obfuscation)

- package.json
Tested the resulting built addon, it no longer sporadically disconnects, and proxies at a nice speed. Hopefully getting this in will also enable more anonymized metrics collection in the near future.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1545)
> freedom-for-firefox onDisconnect fixed

- package.json
- src/chrome/extension/scripts/chrome_tab_auth.ts
- src/generic_core/freedom-module.ts
- src/generic_core/social.ts
- src/generic_core/uproxy_core.spec.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/scripts/core_connector.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/social.ts
- src/interfaces/uproxy_core_api.ts
Modify reconnect logic to support refresh tokens, work in Firefox.
* Now when logging in from the splash screen, we set interactive=true and remember=true.  This causes freedom-social-xmpp to store the refresh token (freedom-social-firebase coming soon...)
* Reconnect attempts set interactive=false and remember=false, to use the last stored refresh token
* Pinging to check if we are connected to the internet has been moved to the uProxy core, so that it will work in Firefox without needing to update package.json for each URL we want to ping.
* Reconnect now works in Firefox, but is only enabled for the 'Google' network (until freedom-social-firebase also supports refresh tokens).
Tested in Chrome and Firefox …
> Modify reconnect logic to support refresh tokens, work in Firefox

- package.json
Remove extra freedom-social-xmpp from package.json, was accidentally merged into previous pull request
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1612)
> Remove extra freedom-social-xmpp from package.json

- package.json
uproxy-libv27.2.1 is, when installed on the sharer's side, is preventing
sharing between plaftorms.  This pins the version at 27.2.0 until we can
figure out what is wrong.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1615)
> Pin uproxy-lib at v27.2.0

- src/generic_ui/locales/all/languages.json
We do not want to make these languages available to users to select until we do a manual pass on translation.  This will disable showing the languages to the users, they will still technically be available though.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1617)
> Disable all languages except English

- src/generic_ui/polymer/description.html
- src/generic_ui/polymer/description.ts
The syntax we were using does not work, this does it a slightly more
ugly but functional way.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1618)
> Switch syntax for the default device description

- src/generic_ui/polymer/logs.html
The text was missing because the Polymer filter was not defined in logs.html
Tested manually
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1620)
> Add text back to logs page.

- package.json
I believe uproxy-lib 27.2.2 fixes the issue described here:
https://github.com/uProxy/uproxy/pull/1615
Tested with Firefox getting access from Chrome.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1628)
> migrate to uproxy-lib 27.2.2, with fix for chrome/firefox issues

- package.json
- src/generic_core/globals.ts
- src/generic_core/remote-connection.ts
This defines `MESSAGE_VERSION` version 3. When a remote peer running this version is encountered, (basic) obfuscation will be offered to them. Older clients will be unaffected.
Tested locally, in the network lab, and across the real internet with a mix of Chrome and Firefox -- but of course we should exercise this quite a bit during the next testing party. If we can't tell the difference during regular browsing, I think we're good to go.
One note: if you experience difficulty establishing a connection in the office, edit your advanced settings to include only `stun.l.google.com`. This only affects the office and we're working on a fix. Of course for any real testing we should be using real home internet and/or mobile connections!
[<img src="https://reviewable.io/review_button.png" …
> enable basic obfuscation

- src/generic_ui/scripts/ui.ts
Previously, when we failed to connect to someone, we would not clear
the UI state that showed we were trying to connect.  This caused the
trying-to-connect message to continue to show in the UI.  With this
change, we now correctly clear that value on failure.
Fixes #1499
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1633)
> Clear which instance we are trying to get access from on proxy failure

- src/generic_core/diagnose-nat.ts
- src/generic_ui/locales/ar/messages.json
- src/generic_ui/locales/en/messages.json
- src/generic_ui/locales/fa/messages.json
- src/generic_ui/locales/fr/messages.json
- src/generic_ui/polymer/settings.html
- src/generic_ui/polymer/troubleshoot.ts
- Added translations for the troubleshoot dialog
- Edited the NAT types to be readable English
- Change the Farsi source to the one that was translated for us
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1657)
> Add missing translations. Update strings for NAT types. Use official Farsi translations.

- src/chrome/extension/scripts/chrome_browser_api.ts
Updating our behaviour to be consistent with what is described at
https://developer.chrome.com/extensions/tabs#method-create so the window
we open tabs in will be focused.  This fixes issues on Linux with not
seeing a FAQ tab opened.
Tested in Linux (using Notion WM) and on Mac (Mac behaviour does not
seem to change)
Fixes #1581
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1668)
> When opening a tab, focus that window

- src/chrome/extension/scripts/chrome_tab_auth.ts
- src/generic_ui/scripts/ui.ts
Support automatic reconnect to Facebook, using background tabs in Chrome.
Facebook unfortunately only supports refresh tokens (called long-lived-tokens) for server-side apps (otherwise we would leak our app-secret).  However Facebook login typically opens a tab which immediately closes, assuming the user is still logged into Facebook (if they are not, they will have to login on that tab).  We can take advantage of this by just performing the typical Facebook login on reconnect.
2 additional changes remain to be done that will make this a slightly better experience:
1. Attempt to re-use the previous Facebook auth token before requesting a new one if interactive==false in the loginOpts for FacebookSocialProvider.login.  This will mean that when a user attempts to reconnect after having only …
> Support automatic reconnect to Facebook, using background tabs in Chrome

- bower.json
Polymer seems to have made a mistake in releasing webcomponentsjs v0.6.2
and has released v0.6.3 which is identical to v0.6.1.  We no longer need
to pin our version at v0.6.1.
Fixes #1585
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1658)
> Stop pinning webcomponentsjs version

- package.json
- setup.sh
This changes the setup.sh script so that we will pass a -f command to rm
in clean (this avoids a failure error code if it is run twice) and
forces us to use the local versions of both bower and grunt giving us
better control over those packages if neded.
This also removes automatically running bower after doing npm install
since the user should, in theory, never run that directly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1634)
> Make the setup.sh script more robust

- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/copypaste.html
- src/generic_ui/polymer/copypaste.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/uproxy_core_api.ts
This aims to reduce the complexity of the copy+paste messages as well as
to reduce the computation necessary to process them.
First of all, this creates a new type for the COPYPASTE_MESSAGE message
data, CopyPasteMessage.  It was previously being treated as a
PeerMessage (type was actually {type :PeerMessageType, data :string}),
and with the other updates, the type is now
{type :PeerMessageType, data :PeerMessage[]}.  This removes the need for
us to do manual type casting.
Second, as alluded to above, we now send the peer messages to the UI as
an array of peer messages instead of doing the encoding within the core.
This, and storing them in this fashion within the UI, allows us the
convenience of only needing to pipe the messages through a filter in
order to get the correct output and …
> Reduce complexity of copy+paste messages

- src/generic_core/globals.ts
- src/generic_core/remote-connection.ts
This `MESSAGE_VERSION` indicates that a client has support for holographic ICE.
Tested in Chrome on my desktop.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1696)
> define MESSAGE_VERSION 4, to use holographic ICE

- src/chrome/extension/scripts/chrome_browser_api.ts
- src/chrome/extension/scripts/chrome_core_connector.spec.ts
- src/firefox/data/scripts/firefox_browser_api.ts
- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/browser_api.ts
The name fulfillLaunched was exposing too much information about the
implimentation a single platform (Chrome) had for what to do when a
popup was launched.  This renames that to handlePopupLaunch and defines
that it should be called once the popup is done registering callback.
The time where it is called is moved from whenever the popup receives
a full state update to calling it as soon as all callbacks have been
registered.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1683)
> Rename fulfillLaunched to handlePopupLaunch

- src/generic_ui/polymer/feedback.ts
- src/generic_ui/polymer/troubleshoot.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/uproxy_core_api.ts
Related issue:
https://github.com/uProxy/uproxy/issues/1659
This adds two new fields to feedback:
* `feedbackType`
* `proxyingId`
These are set when the user submits feedback via the failed to give/get toast.
@lucyhe, does this look right to you in terms of making the website handle these new fields?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1710)
> add type and session id fields to feedback

- src/generic_core/globals.ts
- src/generic_core/remote-connection.ts
- src/generic_core/social.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/uproxy_core_api.ts
This was very useful to help solve this issue:
https://github.com/uProxy/uproxy/issues/1707
This adds a new advanced setting, `force_message_version`. When set, it affects the type of peerconnection offered by `RemoteConnection` (pre-obfuscation, obfuscation, holographic ICE, etc.).
Very very useful for debugging.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1712)
> add a force_message_version advanced setting

- package.json
- src/chrome/app/scripts/chrome_ui_connector.ts
- src/chrome/app/scripts/main.core-env.ts
- src/chrome/extension/scripts/background.ts
- src/generic_core/freedom-module.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/core_connector.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/uproxy_core_api.ts
- third_party/tsd.json
With our current split app/extension design in Chrome, we unfortunately
have to deal with the fact that the two may be of different versions.
In the past, this has been handled by the extension immediately updating
when there was a new version and the app updating whenever the browser
was closed.  This caused us to lose a lot of confidence in them working
together.  In order to fix this, we now handle update messages
ourselves.
When the app has an update available, it will be forwarded to the core
which will store the available version and then forward the information
to the UI.  At this point, the UI will display a notice that an update
is available.  Nothing will happen without user action.
When the extension can update, it will check what the version of the app
is.  If the app is older …
> Add better handling of app/extension updates in Chrome

- src/generic_ui/scripts/ui.ts
When we get a full state message, update the extension icon after
processing the state.  This ensures that if we previously had bad
information (e.g. thought we were offline) we will have correct
information after finishing this.  This does not fully fix issues with
the icon (we will still show it incorrectly after restarting the
extension before the panel is opened), but it is a step in the right
direction.
Fixes #1717
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1722)
> Update extension icon after getting initial state

- src/firefox/lib/firefox_proxy_config.js
Fixes https://github.com/uProxy/uproxy/issues/1772
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1774)
> Enable transparent DNS proxying in Firefox.

- src/chrome/extension/scripts/chrome_browser_api.ts
- src/firefox/data/scripts/firefox_browser_api.ts
- src/firefox/lib/glue.js
- src/firefox/lib/main.js
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/browser_api.ts
Addressing https://github.com/uProxy/uproxy/issues/1547, new icons will be added in another pull request.
Tested manually in C/FF.
Notifications:
(Chrome on top, FF bottom)
Notifications with proxying state:
I think this actually looks good with Firefox, but should we remove the proxying state for both?
Unfortunately the Chrome badge can not be repositioned.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1776)
> Show the number of notifications in a badge over uProxy extension icon.

- README.md
- package.json
- setup.cmd
- setup.sh
`setup.sh` has been translated to the batch file `setup.cmd`, which has the exact same interface and functionality, but will run in Windows (using cmd or PowerShell).
The dependency `tsd` has also been updated from `0.5.7` to `0.6.3`, since the new version removes an (optional) dependency on Python 2.7, which would error on vanilla Windows.
Last, the readme has been updated accordingly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1793)
> uProxy build script for Windows

- Gruntfile.coffee
- package.json
- src/cca/app/index.html
- src/cca/app/manifest.json
- src/cca/app/polymer/browser-elements.html
- src/cca/app/scripts/context.ts
- src/cca/app/scripts/cordova_browser_api.ts
- src/cca/app/scripts/cordova_core_connector.ts
- src/cca/app/scripts/main.core-env.ts
- src/chrome/extension/scripts/chrome_core_connector.ts
Currently the getter functionality is present but nonfunctional,
so the app is titled "uProxy for Sharers".  The Google social network
is also not working, possibly due to STARTTLS issues in the TCP
socket API bindings.
This is the first part of a solution to https://github.com/uProxy/uproxy/issues/586
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1809)
> Enable building uProxy as a Cordova Chrome App for Android

- package.json
- src/generic_core/globals.ts
- src/generic_core/remote-connection.ts
- src/generic_core/remote-instance.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/advanced-settings.ts
This is the uproxy side change for https://github.com/uProxy/uproxy-lib/pull/245.
Now, we use one instance of the `freedom-port-control` module everywhere (stored in the core globals), and probe the router only when uProxy starts up (when uproxy core gets loaded). These two changes should make `portControl.addMapping()` much faster, since we're now keeping track of which protocol has previously succeeded inside the module.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1817)
> Use singleton freedom-port-control to optimize addMapping()

- src/generic_core/uproxy_core.spec.ts
Running grunt test was giving this error:
TypeError: 'undefined' is not a function (evaluating 'portControl.probeProtocolSupport()')
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1833)
> Mock probeProtocolSupport function for uproxy_core.spec.ts

- src/chrome/app/scripts/main.core-env.ts
- src/chrome/extension/scripts/background.ts
- src/firefox/data/scripts/content-proxy.ts
- src/firefox/lib/glue.js
Tested manually for Chrome/FF.
With this change, viewing the test site will show "Launch" instead of "Install"
https://test-dot-uproxysite.appspot.com/
Addressing https://github.com/uProxy/uproxy/issues/1547
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1794)
> Update how uProxy informs (approved) pages that it is installed.

- src/chrome/extension/scripts/chrome_core_connector.spec.ts
- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/instance.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/core_connector.ts
- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/ui.ts
Partially fixes #1825 
Looks like this:
@lucyhe @jpevarnek
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1836)
> Add auto-retry on connection failure.

- setup.cmd
`setup.cmd` will now run on Windows where there are spaces in pathnames.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1814)
> setup.cmd now works with spaces in paths

- src/generic_ui/polymer/copypaste.ts
Fixes #1855
Copy+paste did not get updated at the same time tha the other disconnect
routes did, this fixes that.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1856)
> Actually revert proxy settings when finishing copy+paste session

- src/generic_core/remote-instance.ts
- src/generic_core/social.ts
- src/generic_core/uproxy_core.ts
Resolving: https://github.com/uProxy/uproxy/issues/1788
Previously they were only shown for connections that timed out (e.g. which I saw with bad NAT configs b/w test machine and my mac). This will handle other errors too, e.g. if the peer connection fails to establish the control channel (which I saw in testing).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1862)
> Show a toast for all types of getter/sharer connection failure.

- src/generic_ui/polymer/instance.ts
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/ui.ts
ran grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1863)
> If the user cancels proxying attempt, don't show "failed to get" toast.

- src/chrome/extension/manifest.json
Fixes #1723.  uProxy now continues to run even after all Chrome windows are closed, and runs on startup.  This means that sharers, once they log in (and set persistent login permissions), will not have to login again to be available for sharing.
The main user-visible difference is this notification during installation:
Tested on Windows, using a profile that does not have any other background apps.  After logging into Facebook once, the user was not logged out when closing Chrome, only when logging out of Windows.  Upon logging back into Windows, uProxy reconnected to Facebook but did not display any user interface (apart from a Chrome tray icon).  This only worked if the user checked the "Keep me logged in" checkbox on the Facebook login page.
@jpevarnek @gwpenn
[<img …
> Enable early start in Chrome

- src/generic_ui/polymer/app-bar.html
This makes the selectors for app-bar styles a lot more specific to get
around some errors we were seeing in Firefox.  In Firefox, we were
seeing styles from other elements jump scope and apply to the app-bar,
so we now make sure that will not happen.
Fixes #1845
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1851)
> Make app-bar styles more specific

- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/copypaste.html
- src/generic_ui/polymer/copypaste.ts
We now have a specialized message for when you are no longer sharing
access instead of just telling the user they are no longer getting
access.
This will not work across restarts, that's fine.
Tested manually
Fixes #1592
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1857)
> Add copy+paste message for not sharing

- src/generic_ui/style/global.css
Due to a Chrome change, all core-input elements were force-styled to be
20em wide.  This looked incredibly strange when used with a
paper-input-decorator (as is all over in the code).  This changes the
styling for core-ipnut element below paper-input-decorators so that they
will have the correct size.
Fixes #1878
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1884)
> Fix a bug with core-input sizes

- src/generic_ui/polymer/advanced-settings.html
- src/generic_ui/polymer/avatar.html
- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/description.html
- src/generic_ui/polymer/feedback.html
- src/generic_ui/polymer/instance.html
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/roster.html
- src/generic_ui/polymer/settings.html
- src/generic_ui/polymer/splash.html
- src/generic_ui/polymer/troubleshoot.html
The Chrome handling of dependant styles got changed to give priority to
the parent scope
(https://code.google.com/p/chromium/issues/detail?id=487125) which
causes the styling for core-icon to no longer allow the changing of
height/width using the recommended method.  In order to get around this,
we now spceficy all height/width properties we want to set on a
core-icon as !important (along with some other properties).
Fixes some parts of #1858
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1881)
> Fix issues with core-icon styling

- src/generic_ui/polymer/bubble.html
- src/generic_ui/polymer/button.html
- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/copypaste.html
- src/generic_ui/polymer/description.html
- src/generic_ui/polymer/instance.html
- src/generic_ui/polymer/network.html
- src/generic_ui/polymer/reconnect.html
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/settings.html
- src/generic_ui/polymer/splash.html
- src/generic_ui/polymer/troubleshoot.html
- src/generic_ui/style/global.css
One of the downsides of the Chrome rule changes is /deep/ rules will
pretty much universally tend to override other styles on elements.  In
order to get around this, we switch from trying to style all
paper-buttons at a global scope and now have a uproxy-button (that has
styling) and override the styling for that the way we had before where
necessary.
Fixes #1877
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1882)
> Switch to using uproxy-button

- package.json
- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/copypaste.html
- src/generic_ui/polymer/copypaste.ts
- src/generic_ui/scripts/core_connector.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/uproxy_core_api.ts
This uses the new-fangled gzip compression stuff in uproxy-lib on one-time connection URLs. I also tried to simplify a few things along the way.
One thing to note is that this *doesn't* support older clients. I think it would be pretty straightforward to add, at the cost of pretty ugly code. I'm not sure how important support for older clients is.
Depends on:
https://github.com/uProxy/uproxy-lib/pull/283
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1880)
> compression for one-time connection URLs

- src/generic_ui/locales/ar/messages.json
- src/generic_ui/locales/en/messages.json
- src/generic_ui/locales/fa/messages.json
- src/generic_ui/locales/tr/messages.json
- src/generic_ui/locales/vi/messages.json
- src/generic_ui/polymer/roster.html
No contacts screen now has a FAQ link, which takes the user to the #howDoIFind section:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1895)
> Update no contacts found screen with FAQ link

- src/firefox/lib/glue.js
- src/firefox/lib/main.js
- src/firefox/package.json
Undo Firefox changes for jpm, as they were breaking the dist build.
Entered https://github.com/uProxy/uproxy/issues/1909 to re-add JPM changes later on once we know how to make them support both dev + dist
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1910)
> Undo Firefox changes for JPM

- src/chrome/extension/invite-received.html
- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/accept-user-invite.html
- src/generic_ui/polymer/accept-user-invite.ts
- src/generic_ui/polymer/invite-user.html
- src/generic_ui/polymer/invite-user.ts
- src/generic_ui/scripts/ui.ts
Translate invite UI, and update styles to be slightly closer to the ideal mocks https://folio.googleplex.com/izzie/uProxy/091015_InviteFlow#%2FInvite%20Flow_v3.png%3Fz=half (lots of styling work still remains).
The only part that hasn't yet been translated is invite-received.html, the page which appears in the browser tab when the user navigates to an invite URL.  This is similar to copypaste.html which also is not translated as it doesn't yet use Polymer.
Partly addresses https://github.com/uProxy/uproxy/issues/1908
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1911)
> Translate invite UI

- src/generic_core/uproxy_core.ts
@jpevarnek I'll defer to you on when's a good time to enable this but I figure since support for reading compressed messages has been out for 1-2 releases now, it's about time to enable.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1915)
> enable compression of one-time messages

- src/generic_core/remote-instance.ts
- src/generic_ui/polymer/root.html
This is in two parts: the first makes it so that we will immediately abort an attempt to connect if we lose access (instead of waiting until we time out).  The second part of this makes it so that we will not show the reconnect error in the case where there was no user to reconnect to (i.e. copy+paste).
I wanted to make changes so that the reconnect dialog would show better contextual information about whether you had access to reconnect, however, that does not seem to be possible without reworking a large amount of code for both Core <-> UI communications and the actual UI state storage.  A project for another day :(
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1904)
> Tweaks to reconnect behaviour

- Gruntfile.coffee
- src/generic_core/remote-connection.ts
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-instance.ts
- src/generic_core/remote-user.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/copypaste.html
- src/generic_ui/polymer/copypaste.ts
- src/generic_ui/scripts/copypaste-state.spec.ts
- src/generic_ui/scripts/copypaste-state.ts
- src/generic_ui/scripts/ui.ts
- src/generic_ui/scripts/user.spec.ts
- src/interfaces/social.ts
- src/interfaces/uproxy_core_api.ts
Do a better job of keeping track of the endpoints for active connections, send that information to the UI, and use it to re-enable a proxying connection on extension restart.
Tested manually and by running `grunt test`.
See commit messages for a more detailed view of what was done.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1921)
> Endpoint cleanup fun

- package.json
No change in behaviour, the major version bump was just for a bunch of files that moved around during a big refactor.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1926)
> migrate to latest uproxy-lib

- Gruntfile.coffee
Instead of having to deal with a massive mess of rules every time you
want to add a new test, you can now just add a new .spec.ts file (as
long as it is in generic_ui/scripts or generic_core).
This change looks a lot scarier than it is, so a quick description of
what it really done:
This moves the gruntConfig object to a variable named gruntConfig
This adds a new function to the Gruntfile to look for all the spec files
in a directory and make rules to browserify those files and run them
(return the tasks to run to do that).
This uses that function for generic_ui/scripts and generic_core
That's all!  Sorry about how ugly the diff is going to look...
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1924)
> Make it easier to add tests

- src/firefox/lib/url-handler.js
Fix Firefox URL matching.
Previously URLs used in the Facebook send dialog were triggering the URL handler, resulting in errors.
e.g. this URL should not trigger the event handlers anymore:
```https://www.facebook.com/dialog/send?app_id=%20161927677344933&link=https://www.uproxy.org/invite/eyJ2IjoxLCJuZXR3b3JrTmFtZSI6IkZhY2Vib29rLUZpcmViYXNlLVYyIiwidXNlck5hbWUiOiJEYW5pZWwgQm9ya2FuIiwibmV0d29ya0RhdGEiOiJ7XCJ2XCI6MSxcInVzZXJJZFwiOlwiNjcwNjg0OFwiLFwicGVybWlzc2lvblRva2VuXCI6MTk0NTcxMTYwNzF9In0=&redirect_uri=https://www.uproxy.org/```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1933)
> Fix Firefox URL matching

- .travis.yml
As per:
https://github.com/uProxy/uproxy-lib/pull/264
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1953)
> migrate to travis containers for faster build start times

- package.json
- src/generic/network-options.ts
- src/generic_core/globals.ts
- src/generic_core/social.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/network-in-settings.ts
- src/generic_ui/polymer/network.ts
- src/generic_ui/polymer/quiver-login.html
- src/generic_ui/polymer/quiver-login.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/splash.html
- src/generic_ui/polymer/splash.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/social2.ts
- src/interfaces/uproxy_core_api.ts
* Store quiverUserName in global settings
* Support reconnect in Quiver (using stored name) from both UI (unexpected disconnect) and uProxy restart (https://github.com/uProxy/uproxy/issues/1954)
* Refactor Quiver login screen to be a core-overlay, instead of page within splash.html, to allow it to be re-used when logging in via the settings drawer (https://github.com/uProxy/uproxy/issues/1960)
* Add userName to social2 API to remove version hack (https://github.com/uProxy/uproxy/issues/1955)
Tested in Chrome using latest version of Quiver
Here's a screenshot of the latest Quiver login screen.  It will be translated prior to webstore launch, probably after we restyle everything to move the login screens behind the invite button:
[<img src="https://reviewable.io/review_button.png" height=40 …
> Quiver fixes + cleanup

- src/generic_core/freedom-module.ts
- src/generic_core/social.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/accept-user-invite.ts
- src/generic_ui/polymer/contact.ts
- src/generic_ui/scripts/core_connector.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/social.ts
- src/interfaces/uproxy_core_api.ts
Fix accepting invites:
* remove old addUser method, that was deprecated
* acceptInvitation now takes optional token (url, for Firebase providers) and userId (GitHub)
Tested with GMail (working) and GitHub providers (sending invites are broken - but this was broken before this change anyways)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1997)
> Fix accepting invites

- src/generic/network-options.ts
- src/generic_ui/polymer/invite-user.html
Add invite screen for WeChat, to generate invite URLs.  Note that freedom-social-wechat doesn't yet support invites yet, this is just to help us test.  Since WeChat is only available on the dev build it will not affect users
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2023)
> Add invite screen for WeChat

- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/advanced-settings.html
- src/generic_ui/polymer/advanced-settings.ts
Per: https://github.com/uProxy/uproxy/issues/1176
Added "Analyze NAT" button to Advanced Settings page, modified three files: 
advanced_settings.html, advanced_settings.ts, messages.json (english)
Result:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1966)
> Add "Analyze NAT" button to Advanced Settings page #1176

- src/generic_ui/polymer/faq-link.html
- src/generic_ui/polymer/splash.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2030)
> Make the click (well, tap) targets for the uproxy-faq-links in splash bigger

- Gruntfile.coffee
- package.json
- src/cca/app/manifest.json
- src/cca/app/scripts/cordova_browser_api.ts
- src/cca/app/scripts/main.core-env.ts
- src/generic_core/globals.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/browser_api.ts
- third_party/typings/cordova/cordova.d.ts
- third_party/typings/cordova/inappbrowser.d.ts
- third_party/typings/cordova/splashscreen.d.ts
- third_party/typings/cordova/themeablebrowser.d.ts
This change switches to a custom themeable browser and gets rid of the warning message when you stop using the browser.
With this change, uProxy for Android is minimally functional (provided you build against freedom from master) and basically somewhat usable.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2048)
> Improvements for Android

- src/generic_core/local-instance.ts
- src/generic_core/social.spec.ts
- src/generic_core/social.ts
- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/invite-user.html
- src/generic_ui/polymer/invite-user.ts
- src/generic_ui/scripts/core_connector.ts
- src/interfaces/social.ts
Update permission storage: now in addition to storing permission tokens, we store what access it gives the receiver.  Currently only FRIEND_REQUEST is supported, but this will allow us to more easily add support for granting+requesting access as part of invites.  Also we are now storing the timestamp that a token was generated at in case we decide to expire old tokens in the future
Improve Quiver UI:
* Automatically show invite URLs after logging into Quiver.  These URLs are also automatically selected when clicked on
* X button now closes GMail, Facebook, etc login popups
* Change text to now say "Find your friends on a social network" - which makes sense both before and after the user has logged into the network
* Some code cleanup
This is how it looks before logging into Quiver:
and …
> Improve Quiver UI, update permission storage

- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/roster.ts
- src/generic_ui/scripts/ui.ts
This removes logic for hiding contacts in contact.ts and instead just prevents Cloud contacts from being added to share rosters.
This is so that the "contacts.length" numbers everywhere are correct, and that the Share roster will look empty if we only have Cloud friends.
For example, before this fix, we would see:
Now we will see (as expected):
while the get tab shows:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2079)
> For Cloud, display empty share rosters correctly.

- src/generic_core/remote-instance.ts
This seems to be required for connections between my phone (nexus 4)
and test box (Atom-class server) over a fast connection.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2085)
> Lengthen connection timeout from 30s to 90s

- package.json
Done, finally!
BTW, this does serve to specify the minimum required version of uproxy-lib, and help out anybody who was building against 35.0.1.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2091)
> migrate to uproxy-lib with cloud fix for firefox

- Gruntfile.coffee
- package.json
- src/generic_core/firewall.spec.ts
- src/generic_core/freedom-module.ts
- src/generic_core/globals.ts
- src/generic_core/metrics.spec.ts
- src/generic_core/remote-connection.spec.ts
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-user.spec.ts
- src/generic_core/social.spec.ts
- src/generic_core/social.ts
- src/generic_core/storage.spec.ts
- src/generic_core/ui_connector.spec.ts
- src/generic_core/ui_connector.ts
- src/generic_core/uproxy_core.spec.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/social.ts
- src/interfaces/uproxy_core_api.ts
Make it easier to register commands
This makes it easier to register commands by adding an array we loop
through.
In order to support that, we needed a single function we could call in
order to register a function that may or may not return a promise, this
is done as a new onCommand function.
In order to have a single function, we now have the onCommand do error
checking to determine whether a promise was passed/expected and then
have it send the promise.  Anyways, that's going to take error handling.
Yay!
Because that is confusing, this also adds tests.
Review for this should include answering the question: Does this
actually improve anything?
Also changed:
Switch our unit tests to have single-file scope
Remove the manual social network from the codebase
[<img …
> Update the way we configure freedom-module

- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/accept-user-invite.ts
- src/generic_ui/scripts/ui.ts
Make accept-user-invite screen use same code+logic as invite URLs.  Fixes #2075 (accepting an invite from the accept-user-invite.html screen was failing if you weren't already logged into the network).
Also makes a small change to the cloud invite confirmation text.  Now, regardless of whether the user is logged into Cloud or not, they still see the same confirmation, ```You've entered an experimental Cloud invitation. Accepting this invitation will connect you to a virtual machine. Would you like to accept?```
Tested the following:
* navigating to URLs for GMail, Quiver, Cloud when already logged into those networks
* navigating to URLs for GMail, Quiver, Cloud when not yet logged into those networks
* entering an invite into accept-user-invite.html when already logged into the network
* …
> Make accept-user-invite screen use same code+logic as invite URLs

- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/polymer/settings.html
- src/generic_ui/polymer/settings.ts
- src/generic_ui/polymer/splash.html
- src/generic_ui/polymer/splash.ts
Tested in Chrome/FF in dist and dev. 
For FF this also fixes the extra wide buttons we were seeing on the metrics opt in page.
@dborkan I'm removing the "Anonymous metrics enabled" bubble in this PR too (it made things simpler) so I can wait until you have your changes in before having this reviewed!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2116)
> Move metrics opt-in to the SPLASH view.

- README.md
- Added a line about setting your ANDROID_HOME variable if `node_modules/.bin/cca checkenv` fails
- Split installing the app into two sections for 1) a device and 2) an emulator. Added bullet points to the device instructions and created the emulator section. 
Fixes #1962
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2123)
> Updated build instructions for android

- package.json
This fixes #2084.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2114)
> Update freedom-for-chrome to 0.4.22, which has a socket fix for Cordova

- src/generic_ui/locales/en/messages.json
Update GitHub confirmation text, the new text fits better and also mentions that users need to verify their email addresses:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2138)
> Update GitHub confirmation text

- Gruntfile.coffee
This adds a helper function to the gruntfile, fullyVulcanize, that makes
the process of vulcanization a lot cleaner.  It creates both of the
vulcanize rules and, if we want to do browserification, also creates the
browserify and string-replace rules that are needed there.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2144)
> Add a helper function to make vulcanization cleaner

- src/generic_core/social.ts
Needed to allow freeform userId
This should be compatible with both current and future Quiver
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2155)
> Slight change to Quiver clientId parsing

- Gruntfile.coffee
- src/cca/app/index.html
- Updated cca/app/index.html by uncommenting <script src='../bower/webcomponentsjs/webcomponents.min.js'></script>
- Updated Gruntfile by adding correct commands to build ios; now you can use 'grunt build_ios' or 'grunt emulate_ios' to run uproxy on ios
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2165)
> Updated gruntfile and index.html to build uProxy on ios

- src/generic_core/social.ts
Fixes https://github.com/uProxy/uproxy/issues/1982
Prior to this change, Quiver had been correctly emitting an onClientState event for the logged in user with status='OFFLINE' when the user was disconnected, however uProxy didn't treat it as coming from a valid client and so ignored the message.  With this change, Quiver is recognized as logged out and automatic reconnect is attempted.
Tested with Quiver in Chrome by logging in, then disabling my internet connection for ~1 minute.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2180)
> Fix Quiver disconnect and automatic reconnect

- src/generic_ui/locales/en/messages.json
Goal of this PR is to get the user excited about what's about to happen (after potentially following a bunch of difficult steps), reframe the fact that cloud is experimental as another thing to be excited / feel special about, and remove "virtual machine" (unnecessary technical jargon).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2182)
> improve cloud invite confirm message

- src/generic_ui/polymer/contact.ts
- src/generic_ui/scripts/user.spec.ts
- src/generic_ui/scripts/user.ts
Fix for issue #2011 (offline contacts should be collapsed by default)
- Added logic to collapse offline users by default
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2198)
> Collapsed offline contacts by default

- src/generic_ui/scripts/ui.ts
Fix invite parsing in cases where invite contains "==" (e.g. base64 cloud invites)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2222)
> Fix invite parsing in cases where invite contains "==" (e.g. base64 cloud invites)

- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/faq.html
- src/generic_ui/polymer/invite-user.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/scripts/ui.ts
Add help and FAQ text for Quiver.
This is the new Quiver login screen:
This is the screen users see if they click on a Quiver invite without yet being signed into Quiver:
This is the FAQ entry they see if they click "Learn more":
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2224)
> Add help and FAQ text for Quiver

- Gruntfile.coffee
- package.json
freedomjs-anonymized-metrics now uses a "normal" path structure!
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2237)
> Update freedomjs-anonymized-metrics, fix Gruntfile

- src/generic_ui/scripts/ui.ts
Fix v1 invites (briefly broke due to Quiver changes)
v1 of invites are confusing because the invite contains an object called "networkData", which itself contains a string called "networkData".  Older social providers (e.g. Firebase) expected only the inner networkData string, however due to Quiver changes we had been passing the outer networkData object.  Good news is this mess is cleaned up with v2 invites which we can start moving social providers to use.
here is an example of a decoded v1 invite where you can see the networkData mess:
```
"{"v":1,"networkName":"GMail","userName":"XXX","networkData":{"networkData":"{\"v\":1,\"userId\":\"XXX\",\"permissionToken\":XXX}"}}"
```
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on …
> Fix v1 invites (briefly broke due to Quiver changes)

- package.json
This should do it for firefix, afaict.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2257)
> Firefox metrics fix: Upped package.json to freedomjs-anonymized-metrics 0.7.4.

- src/chrome/app/polymer/ext-missing.ts
- src/chrome/extension/polymer/app-missing.ts
- src/chrome/extension/scripts/background.ts
We made the switch to /install a while back, apparently I forgot to
update it in the actual uproxy extension.  Oops.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2261)
> Replace chrome-install with install for website paths

- src/generic_ui/polymer/invite-user.html
Make login help text darker, requested by @gwpenn 
Login text for GMail, GitHub, etc now look darker, matching what we had been using for Quiver:
GMail:
GitHub:
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2233)
> Make login help text darker

- src/generic/network-options.ts
- src/generic_core/social.ts
This fixes an issue when a Quiver client auto-reconnects on all
servers at once (e.g. when waking from suspend).  Peers see a
new client come online, but they do not see a new instance
message, so they do not make the new client visible in the UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2300)
> Enable monitoring for Quiver, and shorten the monitoring interval.

- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/cloud-install.html
- src/generic_ui/polymer/cloud-install.ts
- src/generic_ui/scripts/core_connector.ts
- src/generic_ui/scripts/model.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/uproxy_core_api.ts
after cloudInstall we now:
* sign into the Cloud social network if we aren't yet logged in
* add ```isAdmin=true``` to the object returned by the installer
* pass this networkData to ```acceptUserInivtation```
```cloudInstall``` also now just returns a ```Promise<void>```, since the UI doesn't need to know the invite anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2305)
> Add newly deployed cloud friend to roster

- src/generic_ui/locales/ar/messages.json
- src/generic_ui/locales/en/messages.json
- src/generic_ui/locales/fa/messages.json
- src/generic_ui/locales/tr/messages.json
- src/generic_ui/locales/vi/messages.json
- src/generic_ui/polymer/cloud-install.html
- src/generic_ui/polymer/invite-user.html
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/polymer/roster.html
* Get rid of get/share welcome popup
* Make help text areas on the empty roster shorter, so there isn't ugly overlap with the + button
* Make the lines lighter color on the invite-user screen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2321)
> Cloud UI cleanup

- src/generic_ui/polymer/invite-user.ts
Previously, after clicking "Continue" on this screen:
you would end up back on this screen:
Now, clicking "Continue" will take you back to the roster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2333)
> Close invite user panel before opening Cloud install panel.

- src/generic_core/uproxy_core.ts
- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/cloud-install.html
- src/generic_ui/polymer/cloud-install.ts
- src/generic_ui/polymer/contact.ts
- src/generic_ui/scripts/ui.ts
- If a 'uproxy-cloud-server' already exists when we are trying to create a new server, `serverExistsOverlay` in cloud-install is shown
- When user selects Remove Server and Try Again, we delete the uproxy-cloud-server then remove the locally created cloud server contact in `removeServerTapped()`
- We call `getCloudUser()` in ui.ts to find a locally created cloud user if one exists
- Updated along with: https://github.com/uProxy/uproxy-lib/pull/379
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2357)
> Delete cloud server if one already exists

- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/roster.html
Fixes #2356 and #2332 .  Also fixes profile link which was incorrectly hidden sometimes
Tested in Chrome (on various window sizes) and Firefox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2363)
> Fix resizing empty roster, re-add contact image

- src/generic_core/uproxy_core.ts
- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/cloud-install.html
- src/generic_ui/polymer/cloud-install.ts
- src/generic_ui/scripts/ui.ts
Recreating a pull request due to some big merge conflicts; primary review for this PR is at https://github.com/uProxy/uproxy/pull/2367
Overview:
- Keeping track of provisioners and installers in cloudInterfaces object in uproxy_core so that we can destroy them to cancel the install process
- Added cancel button to installingOverlay; button is disabled with ui.cloudInstallCancelDisabled if we are in the removing stage (if a server already existed) or the configuring ssh stage (which is the last stage and only lasts a few seconds)
- Added cancelingOverlay because canceling a cloud server can take up to a couple minutes if you try to cancel it at the very beginning. According to what I've read on Digital Ocean, you can't destroy a server while another action is in progress so we have to wait …
> Adding functionality to cancel cloud creation

- Gruntfile.coffee
Some parts of our Gruntfile seem to have issues with different versions
of coffeescript.
I'm very open to better ways of writing that...I think it just looks weird no matter what.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2384)
> Make syntax change in coffeescript

- src/generic_core/uproxy_core.ts
- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/contact.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/uproxy_core_api.ts
When the user fails to get access to a locally created cloud server, we give the user the option to restart the server. 
With uproxy-lib PR: https://github.com/uProxy/uproxy-lib/pull/401
Getting confirmation to restart:
Toast shown when server is rebooting:
Toast shown when restart is successful:
Dialog shown if restart fails:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2393)
> Added restart cloud option when connection fails

- src/generic_ui/polymer/contact.html
Move all per-contact icons onto a single line instead of having the
open/close icon be to the right of everything else.  Get rid of the
wrapper that was serving little purpose.  Remove the table that was
causing issues with responsiveness.
Fixes #2359
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2391)
> Simplify icon logic for contact icons

- .shippable.yml
- .travis.yml
See https://github.com/uProxy/uproxy/issues/2396
Seems the C++11 warning isn't really blocking, let me know if we should leave the above issue open anyway or mark it closed after this. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2398)
> up node to 4.4 LTS on shippable/travis

- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/cloud-install.ts
- src/interfaces/social.ts
Several fixes to try to address https://github.com/uProxy/uproxy/issues/2397, and others.
Two main things:
* Reduce the amount of state, particularly in the core where we were trying to keep track of the provisioner module.
* Simplify how we cleanup the module instances, by introducing a function which guarantees to destroy the instance after using it.
Would you agree this reads better?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2420)
> cleanup the cloud operations in core

- src/generic_ui/scripts/content_digitalocean.js
This fixes the overlay in Firefox, using a terrible, terrible hack.
@jpevarnek If you can fix this in a better way before @trevj has to upload the FF release, please do.
Here's a screenshot to prove it works:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2437)
> fix DO overlay in FF

- Gruntfile.coffee
- src/cca/app/config.xml
- src/cca/app/scripts/cordova_browser_api.ts
- src/cca/app/scripts/iosrtc-register-globals.js
- src/cca/app/scripts/main.core-env.ts
- third_party/typings/cordova/webintents.d.ts
With this change, uProxy for Android can now process invite links
that the user taps in e-mail or chat apps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2412)
> Add invite link support for Android.

- src/generic_core/social.ts
Without this, trying to share a Cloud instance generated invites which were marked for Quiver: e.g. uproxy.org/invite?v=2&networkName=**Quiver**&....
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2446)
> Use correct network name in v2 invites for Cloud.

- bower.json
The web-animations library was broken due to
https://bugs.chromium.org/p/chromium/issues/detail?id=601672
With this change, we will use a version of the library that has been
backported with the fix.
Fixes #2465
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2466)
> Force us to use web-animations-js#1.0.8

- package.json
Still not semantic versioning or anything but figured this wouldn't hurt, since we just imported >1000 commits from uproxy-lib.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2468)
> bump minor version number, for uproxy-lib merge

- src/generic_ui/polymer/advanced-settings.html
- src/generic_ui/polymer/advanced-settings.ts
This is a reference commit for what should be done to remove calculated
properties from a Polymer element (necessary to the .5->1.0 transition).
Essentially, the only operation that can now be done in the element is
negation.  All other operations need to be moved to functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2475)
> Remove calculated properties from advanced-settings.html

- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/cloud-install.html
- To maintain alphabetical order, regions are displayed as follows:
Asia (Bangalore)
Asia (Singapore)
Europe (Amsterdam)
NOrth America (New YOrk)
- Move default selection to be Bangalore to start at top of list. Thoughts? Do we want Singapore to be default? And if so, should we go away from alphabetical order so Singapore would be the first option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2471)
> Added Bangalore region as option for Digital Ocean cloud server

- src/cca/app/scripts/context.ts
- src/firefox/data/scripts/background.ts
- src/generic_ui/polymer/state.ts
- src/generic_ui/scripts/same_context_panel_connector.ts
We were accessing an undefined variable for the CCA build, this switches
to using a common framework for the "message passing" between the panel
and the background in CCA and Firefox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2505)
> Attempt to fix CCA issues

- src/generic_ui/polymer/network-invite-user.ts
The invite link we were sending to Facebook was not encoded as a URI
component, this fixes that so it is.
Fixes #2524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2525)
> Encode the link we send to Facebook

- Gruntfile.coffee
- src/chrome/app/managed_policy_schema.json
- src/chrome/app/manifest.json
Got the policy schema working and tested now. This builds locally so there *shouldn't* be any issues (crosses fingers).
To test this, I did the following:
1. Made changes to manifest, managed policy schema, and grunt coffee script.
2. grunt build from local (no errors encountered).
3. Created development app and extension in Chrome web store.
4. Updated externally connectable id and key in the manifest for app and extension (the built ones under build/dev/uproxy/chrome) to match the new development web store entries.
5. Uploaded zipped app and extension folders to web store.
6. On admin console configured the app and extension to be force installed.
7. Added configured policy to the app entry.
8. Waited an hour for web store to finish publishing (they claim this could take up to 60 …
> Managed Chrome Policy Schema

- Gruntfile.coffee
- src/cca/app/scripts/cordova_browser_api.ts
- src/chrome/extension/scripts/chrome_browser_api.ts
- src/firefox/data/scripts/firefox_browser_api.ts
- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/instance.html
- src/generic_ui/polymer/instance.ts
- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/browser_api.ts
- third_party/typings/cordova/device.d.ts
- third_party/typings/cordova/tun2socks.d.ts
This PR adds VPN support for Android.
* Added two Cordova plugins: 
* tun2socks: intercepts all device traffic through VPN and forwards it to uProxy's SOCKS local server. 
* device: provides software/hardware information about the device.
* UI changes:
* Show a 'Start VPN' button for Android VPN-enabled devices.
* User can select whether to start browsing in-app or whole device VPN.
* TODOs
* Localize button strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2535)
> Android VPN

- src/generic_core/globals.ts
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/model.ts
- src/generic_ui/scripts/translator.ts
- src/generic_ui/scripts/ui.ts
Suppose your browser language settings are set as follows:
i.e. Your first preferences is for Farsi, your second is for US English, and your last preference is for any kind of English.
This results in `navigator.languages` in your browser's javascript environment getting set to:
```javascript
["fa", "en-US", "en"]
```
With this change, rather than always initializing the user's language setting to `"en"`, we now initialize it to the first language in `navigator.languages` which we have available, falling back to `"en"` if none match.
Fixes #1693.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2539)
> initialize language setting based on browser settings

- src/generic/network-options.ts
- src/generic_ui/polymer/invite-user.html
- src/generic_ui/polymer/invite-user.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/social.ts
We haven't really cared about experimental networks for a while, this
just finishes removing the leftover mentions of them in our code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2555)
> Remove the concept of an experimental networks

- src/generic_ui/polymer/instance.html
- src/generic_ui/polymer/instance.ts
The wrapper div in instance.html had a hidden field that was redundant
with one in contact.html, this probably won't have a noticable effect,
but would potentially speed things up if a user had a lot of instances
visible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2554)
> Remove hidden attribute from wrapper div in instance

- src/generic_core/globals.ts
- src/generic_ui/polymer/splash.html
- src/generic_ui/polymer/splash.ts
- src/generic_ui/scripts/model.ts
- src/interfaces/uproxy_core_api.ts
The only reason we would want to keep splashState in globalSettings is
to ensure that if the user closes uproxy while on the metrics screen,
they are taken back to the metrics screen instead of the screen before
it.  That takes a lot of overhead to do, so this change removes that
functionality.
This does theoretically break backwards-compatibility between the app
and the extension, however, since splashState would be in storage for
anyone who had just upgraded the app, that's even more unlikely than
usual to come up.
This is in support of #2556 and indirectly #1900 (Polymer 1.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2557)
> Remove splashState from global settings

- src/generic_ui/polymer/contact.html
- src/generic_ui/polymer/contact.ts
We pass the mode a specific uproxy-contact is being used for into the
element, use this mode when deciding how a contact should appear.
This is in support of #2556 and indirectly #1900 (Polymer 1.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2561)
> Remove contact.html dependency on global mode

- src/generic_ui/polymer/roster.html
- src/generic_ui/polymer/roster.ts
This remose the dependencies on data from ui and model in roster.html
and roster.ts.
In roster.html, we are able to remove the dependency on
model.globalSettings.mode by instead looking at the mode attribute given
to the element (which mode it is for).  We can do this because it's fine
for the get roster list to be displaying "OFFERS" even when it's hidden.
In roster.ts, we can remove the dependencies on looking at the contacts
by instead just looking at the contacts specifically passed into this
roster object.
This also removes the (now unused) loadingContacts variable.
This is in support of #2556 and indirectly #1900 (Polymer 1.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Remove global data dependencies from roster.*

- src/generic_ui/scripts/ui.ts
We were mistakenly calling the code to get a description of a
confirmation dialog when we only actually wanted a mesagge dialog, this
fixes that issue.
Fixes #2577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2587)
> Fix error with showing confirmation dialog instead of message

- src/generic_ui/polymer/root.html
By using a core-icon-button for the menu button, we get a
correctly-sized click target.
Fixes #2407
Fixes #2548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2591)
> Make the menu button an actual button

- src/generic_ui/polymer/roster-group.html
- src/generic_ui/polymer/roster-group.ts
- src/generic_ui/polymer/roster.html
- src/generic_ui/polymer/roster.ts
This has been pseudo-removed for a while, I'd like to just kill it while
we're here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2559)
> Completely remove support for roster search queries

- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/ui.spec.ts
- src/generic_ui/scripts/ui.ts
When updating gettingStatus and sharingStatus in the UI, we now send a
signal noting that they have changed instead of our previous behaviour
of just updating shared variables.
It seems very possible that we could reduce the complexity further by
looking at more underlying data (e.g. instanceGettingAccessFrom,
offeringInstances) but that seems unnecessary for this project.
This is in support of #2556 and indirectly #1900 (Polymer 1.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2594)
> Stop using state sharing for gettingStatus/sharingStatus

- Gruntfile.coffee
This is a little bit of a hack, but it's a good one. Turns out when you copy `build/dev/uproxy/lib/samples/zork-node` to a location outside of the git repo, node can't find freedom-for-node - I guess we've been implicitly relying on that top-level node_modules folder. Oops. This is bad for our Docker containers, where we copy/mount only `build/dev/uproxy/lib/samples/`.
This just-makes-it-work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2595)
> add an install step to install freedom-for-node for zork-node

- src/generic_core/local-instance.ts
- src/generic_core/social.ts
- src/generic_ui/scripts/ui.ts
(except for in digitalocean/provisioner.ts, which has already been
done on the jab-improve-DO-oauth branch (to be merged soon))
ref: #2553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2596)
> replace all substr() calls with substring()

- src/generic_core/globals.ts
- src/generic_ui/polymer/settings.html
- src/generic_ui/scripts/model.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/uproxy_core_api.ts
There is no situation under which we actually want to have the cloud
network show up in the settings page, this removes the possibility of
that happening.
Fixes #2603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2607)
> Remove showCloud setting

- replace_xwalk_in_apk.sh
4-byte alignment is required by the Play Store.
Fixes #2575
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2608)
> Produce aligned apks that include our modified crosswalk build.

- src/cca/app/config.xml
A change in the most recent version of cordova-custom-config imposed
additional restrictions on the intent-filter element, which resulted in
our intent-filter not being added to the final configuration.  This
change makes us conform to the new restrictions, and fixes intent
support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2613)
> Fixes intents on Android

- src/generic_ui/locales/en/messages.json
- src/generic_ui/polymer/feedback.ts
Fixes: https://github.com/uProxy/uproxy/issues/2615
We were getting an error message because "this.$.errorInput.selected" was set to the enum value of the feedback type, rather than the index of the paper-item the user selected in the dropdown. The messages map assumed it was the index of the paper-item.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2618)
> Stop showing error message after feedback sends.

- src/generic_ui/polymer/root.html
Probably my fault since I remember consolidating all the signals into one element...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2621)
> Fix bad close tag for core-signals

- Gruntfile.coffee
AFACIT, anyway. Spent some time looking at how Android is built and this stuck out to me. If there is, a `clean` rule would probably be better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2630)
> no need to rm android build before each build

- replace_xwalk_in_apk.sh
According to the [changelog](http://tiswww.case.edu/php/chet/bash/NEWS) negative array indices were only added to bash in the most recent minor version (i.e. 4.3, see item `x.`).
Even the latest version OS X (10.11.6 as of this moment) ships an ancient version of bash in `/bin/bash` (3.2.57).
As a result, our current use of the array index `-1` causes `replace_xwalk_in_apk.sh` (and consequently `grunt build_android`) to fail on OS X:
```
./replace_xwalk_in_apk.sh: line 69: ZIPALIGN_TOOLS: bad array subscript
```
Rather than force OS X users to upgrade to a newer bash (and change our shebang to `#!/usr/bin/env bash` if we don't want to force them to clobber their system bash), we can spell "last element" in the more verbose but backwards-compatible way here.
---
This change is [<img …
> replace negative array index with backwards-compatible spelling

- src/generic_ui/polymer/i18n-filter.ts
- src/generic_ui/polymer/invite-user.html
- src/generic_ui/polymer/logs.ts
- src/generic_ui/polymer/network-invite-user.html
- src/generic_ui/scripts/translator.ts
Fixes https://github.com/uProxy/uproxy/issues/2643
Translations weren't working because there was an extra "setLng" called in logs.ts that kept setting the language back to English.
This also: changes the Polymer filter to depend on translator.ts instead of ui.ts, and removes i18n-filter.html imports where they're not needed (since it's imported at the top level in root.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2645)
> Tweaks for translation.

- src/generic_ui/polymer/roster.html
Observed in latest master on a Nexus 5
Before this change:
With this change:
(Funny this didn't show up for me in desktop Chrome or Firefox on OS X when I "fixed" it the first time in a6e37c83.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2654)
> align down arrow in empty roster on Android properly

- src/generic_core/remote-connection.ts
- src/lib/rtc-to-net/rtc-to-net.ts
I added small amount of code that measures the bandwidth of each session in a connection every 5 seconds. It measures the bandwidth usage just over those 5 seconds, and not the whole time the session was running, because when eventually trying to limit bandwidth usage, a low average with a random high spike cannot be caught with that method. Bandwidth is calculated as bits/second.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2625)
> Measure bandwidth for each individual session in a connection

- src/cca/app/scripts/cordova_browser_api.ts
- src/generic_ui/scripts/ui.ts
* This change **partially** fixes #2644. 
* On Chrome, it is now possible to reconnect to a proxy through the 'Try again' button.
* No regressions introduced on Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2649)
> Allow proxying to restart by not resetting the access mode on stop

- Gruntfile.coffee
Running `grunt build_android` after a successful `grunt build_android` invariably fails, apparently due to #2630. This reverts that change, and also renames the related tasks to use the term "clean" as suggested in #2630. With this change it is again possible to run `grunt build_android` twice in a row successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2664)
> revert #2630 + suggested refactor

- Gruntfile.coffee
- src/cca/app/scripts/cordova_browser_api.ts
- src/chrome/extension/scripts/chrome_browser_api.ts
- src/firefox/data/scripts/firefox_browser_api.ts
- src/generic_ui/polymer/cloud-install.html
- src/generic_ui/polymer/cloud-install.ts
- src/generic_ui/polymer/faq.ts
- src/generic_ui/polymer/invite-user.html
- src/generic_ui/polymer/invite-user.ts
- src/generic_ui/polymer/network-invite-user.html
- src/generic_ui/polymer/network-invite-user.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
- src/generic_ui/scripts/ui.ts
- src/interfaces/browser_api.ts
- third_party/cordova/app.d.ts
- third_party/cordova/backbutton.d.ts
To start with, we add, to most of the views that include a
panel/overlay/dialog, an `opened` property that simply states whether
that panel is active and a `close` method that closes the panel.
For the `invite-user` view, we use the method back instead of close.  In
this case, there are multiple different panels that it might have open
instead of being the main panel itself and we want to make sure we close
the correct (active) one only.
In order to handle the overall functionality of the back button, we now
listen in root.ts for the backbutton core signal.  Our handler there
then cycles through the possible things that could be the top-level
element and closes whichever one that is.  If there is nothing else
open, we close the entire app with a new method that's been added to the
browser …
> Add sane behaviour to the Android back button

- src/generic_core/dev_build/freedom-module.json
- src/generic_core/globals.ts
- src/generic_core/metrics.spec.ts
- src/generic_core/metrics.ts
- src/generic_core/social.spec.ts
This target produces a special release build that has metrics
reporting disabled, so that it can be used for automated or
random testing without contaminating our usage metrics.
This also introduces a mechanism for various builds to include
different default settings.
Arguably required for #2673.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2692)
> Make dev builds use no-op stats reporting.

- package.json
Oops, I did a bunch of work to move over to Node.js crypto calls and forgot to remove this!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2725)
> remove unused crypto dep

- Gruntfile.js
- src/generic_core/remote-connection.spec.ts
- src/generic_core/remote-instance.spec.ts
- src/mocks/rtc-to-net.ts
- src/mocks/socks-to-rtc.ts
Fixes:
https://github.com/uProxy/uproxy/issues/2727
A few things had happened:
* incomplete removal of `SocksToRtc`'s freedom.js wrapper forgot to update the `SocksToRtc` mock https://github.com/uProxy/uproxy/pull/2635
* Tor re-proxy UX work forgot to update the `RtcToNet` mock https://github.com/uProxy/uproxy/pull/2602
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2730)
> fix broken generic_core tests

- Gruntfile.js
- src/cca/app/config.xml
* Register Grunt task to build only modified CCA files (i.e. html, typescript), and not recreate the environment.
* Add [cordova-build-architecture](https://github.com/MBuchalik/cordova-build-architecture) in order to only build an ARM APK - previously, built both ARM and x86 APKs.
* Improves the first invocation of `grunt build_android` by ~20%. Subsequent `grunt build_android_cca` tasks improve the current performance by ~75%.
* See #2720 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2741)
> Improve Android build performance

- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/settings.html
- src/generic_ui/polymer/settings.ts
Fix https://github.com/uProxy/uproxy/issues/2349:
* The "Log-out of uProxy" button should not appear if the user's only logged-in network is cloud
* If the user does click "Log-out of uProxy" (available when they are logged into a non-cloud social network), this should log out of all networks except cloud
* Added a sanity check in the logout method uproxy_core.ts to fail if the UI attempts to logout of cloud.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2747)
> Prevent user from accidentally logging out of cloud social network

- src/generic_ui/polymer/invite-user.ts
I can't think of or find any reason for the current behavior, but maybe I'm missing something.
Before this change:
Note the momentary display of the empty roster before showing the cloud panel, creating a briefly jarring transition. This can be worse on mobile, where hardware is less powerful and [unfortunate resize hacks](https://github.com/uProxy/uproxy/issues/2743) conspire to give UI animations quite the hard time.
Also note that after hitting back, the UI jumps all the way back to the empty roster, rather than going back to the invite screen.
After this change:
Smoother UX, no?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2744)
> don't close invite panel before showing cloud panel

- src/generic_ui/scripts/ui.ts
* Fixes #2740 by only clearing the proxy settings (in Chrome) and stopping the VPN (in Android) when there is no connection switch, i.e. the user hits stop or the proxy gets disconnected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2749)
> Allow handover when starting a connection without stopping the previous

- src/cca/app/index.html
- src/cca/app/scripts/context.ts
- src/cca/app/scripts/workarounds.ts
- src/generic_ui/polymer/root.html
- src/generic_ui/polymer/root.ts
proof of concept, let's discuss
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2751)
> workaround for #2659, caused by #2743

- src/generic_ui/scripts/ui.ts
* Previously, starting multiple connections simultaneously resulted in a race condition, won by the last connection to succeed.
* This fix ensures that all pending proxying attempts will be cancelled and only the latest one will be allowed to continue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2756)
> Fix race when starting multiple connections simultaneously

- src/generic_ui/scripts/background_ui.ts
Before:
After:
Fixes #2772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2773)
> Fix toast message

- src/generic_ui/scripts/ui.ts
- third_party/generic/uparams.d.ts
See https://github.com/uProxy/uproxy/issues/2782 for details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2783)
> Change uparams to no longer use ES6 imports

- .gitignore
Notably, `build/typings`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2791)
> remove a bunch of old stuff from .gitignore

- README.md
We don't use Shippable anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2794)
> remove references to shippable

- src/generic_core/remote-user.ts
- src/generic_core/social.ts
- src/generic_core/uproxy_core.ts
- src/lib/cloud/social/provider.ts
- src/lib/net/pinger.ts
Check if a cloud server is online.  This is needed now that we will be deploying cloud servers from the uProxy website, invites will be generated ASAP even though the server will not be ready for 2+ minutes.
With this change:
* We ping each cloud server once per minute to see if it's online or offline.
* We stop pinging a cloud server if it's removed from the buddylist
* We no longer log out of cloud when the last server (contact) is removed from the buddylist (this was causing error messages to appear because social.logout rejects for Cloud)
* uProxy no longer attempts to send an instance message to Cloud servers (this was resulting in error trace and is not needed by the server)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Check if cloud server is online

- src/cca/scripts/tun2socks_vpn_device.ts
For some reason I'm not getting that event on the browser. I think the CCA app already waits for the Cordova plugins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2809)
> Fix tun2socks_vpn_device

- src/cca/bower.json
- src/cca/index.html
This replaces the current placeholder titlebar with Polymer's `paper-toolbar` element:
https://elements.polymer-project.org/elements/paper-toolbar?view=demo:demo/index.html&active=paper-toolbar
I checked with UX and, background colour excepted, they're okay with the default height, etc., stylings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2832)
> use paper-toolbar in air client

- Gruntfile.js
Something changed recently:
https://github.com/dpa99c/cordova-custom-config/commit/2e1d5d686ac31d3a01d17efbe625de4ff0cd86ce#diff-04c6e90faac2675aa89e2176d2eec7d8
`cca` doesn't seem to support this method...next-to-most recent NPM still works fine - this unbreaks the Android build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2834)
> fix android build by specifying cordova-custom-config version

- src/chrome/app/scripts/main.core-env.ts
- src/chrome/extension/scripts/background.ts
- src/chrome/extension/scripts/chrome_core_connector.spec.ts
- src/generic_core/firewall.spec.ts
- src/generic_core/remote-instance.spec.ts
- src/generic_core/remote-user.spec.ts
- src/generic_core/remote-user.ts
- src/generic_core/social.spec.ts
- src/generic_core/ui_connector.ts
- src/generic_core/uproxy_core.ts
- src/generic_ui/polymer/advanced-settings.ts
- src/generic_ui/polymer/settings.ts
- src/generic_ui/polymer/state.ts
- src/generic_ui/scripts/ui.ts
- src/lib/bridge/bridge.spec.ts
- src/lib/integration-tests/socks-echo/base-spec.core-env.ts
- src/lib/loggingprovider/loggingprovider.ts
- src/lib/nat/probe.ts
- src/lib/net/linefeeder.spec.ts
- src/lib/rtc-to-net/rtc-to-net.ts
- src/lib/socks/headers.ts
- src/lib/transformers/defragmenter.ts
- src/lib/webrtc/peerconnection.spec.ts
- src/lib/webrtc/peerconnection.ts
- src/tslint.json
I was working on some code this morning and spent ages debugging an issue only to eventually realise I had redeclared (shadowed) a variable. Argh, can't tslint help with that? Yes it can.
This adds three more tslint rules:
* https://palantir.github.io/tslint/rules/no-shadowed-variable/
* https://palantir.github.io/tslint/rules/no-duplicate-variable/
* https://palantir.github.io/tslint/rules/no-use-before-declare/
The last two would actually be superceded by https://palantir.github.io/tslint/rules/no-var-keyword/ but I figure we're some way from that :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2847)
> add some more anti-undeclared variable-type lint warnings

- src/lib/socks/node/server.ts
- src/lib/zork/zork.ts
Hey @trevj, I realized I could listen for ice connection state changes to track the current number of getters with active peer connections, so I implemented that here. I think this now correctly matches the intended behavior.
I also added support for getting access from multiple peers at the same time, which required a small change to NodeSocksServer. (Just needed to expose the underlying net.Server.address() method, so that when we currently have a giver and therefore are already running a socks server on the base port, we can pass 0 for the port, and then query for what it turned out to be once we're listening.)
Also added some explanatory comments and a few more small corrections and code improvements.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> fix numGetters logic, support getting from multiple peers simultaneously

- src/lib/socks/node/socket.ts
- src/lib/zork/zork.ts
#2848 changed the numGetters tracking logic to check for ice connection state changes to the 'connected' and 'disconnected' states to update numGetters accordingly. This logic starts here: https://github.com/uProxy/uproxy/pull/2848/files#diff-1978b1ecb88355bcd34e7e58e5828653R198
But I just noticed #1511, in which @bemasc says: "In principle 'disconnected' may fire after 5 seconds of no response, but the connection may automatically transition back to the 'connected' state if pings start working again within 30 seconds." That would make the implementation above quite oversensitive.
I noticed our current code uses a heartbeat approach to track connection health (search [peerconnection.ts](https://github.com/uProxy/uproxy/blob/ffab27e6/src/lib/webrtc/peerconnection.ts) for "heartbeat"). This …
> backpressure, heartbeat datachannel, numGetters, misc.

- src/lib/samples/zork-firefoxapp/index.js
- src/lib/zork/freedom-module.ts
This pull request modifies the Zork Firefox app so that it will set a isMetricsEnabled flag to true iff a "/zork-options" JSON file exists on that machine (i.e. Zork docker container) with ```"isMetricsEnabled": true```.
Note currently isMetricsEnabled is not yet used, and the Zork install scripts are not yet setting this file.  This just lays the groundwork for enabling server-side metrics.  Next changes will be:
* Setting this file in the docker install scripts
* Reporting metrics from the server if ```isMetricsEnabled==true```
* Asking users to opt into metrics collection during server creation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2855)
> Setting isMetricsEnabled flag in Zork Firefox app based on options file

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2860)
> use native travis support for yarn

- docker/sshd/issue_invite.sh
This was a bug introduced in https://github.com/uProxy/uproxy/pull/2868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2873)
> FIX: key supplied to run_cloud.sh was not being written to authorized_keys

- docker/sshd/issue_invite.sh
Addendum to https://github.com/uProxy/uproxy/pull/2873
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2874)
> FIX: keys were not being base64-decoded before being written to authorized_keys
