uProxy/uProxy-p2p

src/chrome/app/manifest.json, src/chrome/extension/manifest.json
ran grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/787)
=> Update version number.

src/chrome/app/manifest.json, src/chrome/extension/manifest.json
ran grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/789)
=> Update version number to 0.5.3.

src/chrome/app/manifest.json, src/chrome/extension/manifest.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/791)
=> update chrome minimum version

package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/793)
=> Update package.json to get the latest versions of freedom repos

src/generic_core/user.ts
https://github.com/uProxy/uproxy/issues/830
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/834)
=> fix instanceId keys

src/generic_core/social.spec.ts, src/generic_core/social.ts
fixes https://github.com/uProxy/uproxy/issues/831
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/835)
=> do not reset myInstance to null

src/generic_core/user.ts
fixes https://github.com/uProxy/uproxy/issues/745
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/836)
=> save to storage when user profile is updated

src/chrome/extension/app-missing.html, src/generic_ui/index.html, src/generic_ui/polymer/contact.html, src/generic_ui/polymer/root.html, src/generic_ui/polymer/settings.html, src/generic_ui/polymer/splash.html
This takes the app closer to being responsive and should remove the
scrollbars when opened in a smaller-than-expected window.
Tested by resizing window on Chrome, opening with Firefox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/822)
=> Removed some height/width restrictions

src/generic_ui/scripts/ui.ts
https://github.com/uProxy/uproxy/issues/866
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/877)
=> add 5 second timeout to notifications in chrome

package.json, src/generic_core/remote-instance.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/900)
=> pull new uproxy-lib and uproxy-networking npms

src/generic_core/core.ts, src/generic_core/social.spec.ts, src/generic_core/social.ts
don't block login promise on storage read
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/876)
=> fix recursive logout calls

src/firefox/README.md
I keep forgetting these instructions + end up digging up a picture of a post-it on my phone. Not sure if these steps will change, if we think they're rather set than maybe we can add it to the main README.
(Is there a way I can preview the README, with the nice Github formatting?)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/901)
=> Update Firefox README

src/generic_ui/polymer/root.html
Closes #913 
Tested by manipulating the UI
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/921)
=> Make the header and footer on the contact list fixed

Gruntfile.coffee, src/chrome/app/scripts/background.ts, src/firefox/lib/main.js, src/generic_core/core.ts, src/generic_core/freedom-module.json, src/mocks/freedom-mocks.ts
Configure with INFO (`*:I`) level throughout for now.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/931)
=> load and configure loggingprovider so we get networking-land logging

Gruntfile.coffee, src/chrome/extension/manifest.json, src/chrome/extension/scripts/background.ts, src/firefox/data/scripts/firefox_browser_api.ts, src/firefox/lib/glue.js, src/firefox/lib/main.js, src/firefox/lib/url-handler.js, src/generic_core/core.ts, src/generic_core/freedom-module.json, src/generic_core/remote-connection.ts, src/generic_core/remote-instance.spec.ts, src/generic_core/remote-instance.ts, src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/copypaste.ts, src/generic_ui/polymer/root.html, src/generic_ui/polymer/splash.html, src/generic_ui/polymer/splash.ts, src/generic_ui/scripts/core_connector.ts, src/generic_ui/scripts/ui.spec.ts, src/generic_ui/scripts/ui.ts, src/uproxy.ts
This is not finished yet, I'm just wanting to get a checkin right now of how things are looking and make sure I am not doing anything horribly wrong.
* There are no tests (besides what already existed for RemoteInstance)
* URL handling is not supported in Firefox
* URL handling will close an existing tab if you click a link that does not have a target set in the Chrome browser
* Occasional bug where URLs get processed twice
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/925)
=> CopyPaste Checkin

src/chrome/extension/polymer/app-missing.ts, src/chrome/extension/scripts/background.ts, src/chrome/extension/scripts/dependencies.js
Ran grunt test
https://github.com/uProxy/uproxy/issues/899
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/916)
=> Auto-advance from app-missing.html to index.html if app is installed

src/generic_core/core.ts, src/generic_core/social.ts, src/generic_ui/polymer/network.html, src/generic_ui/polymer/network.ts
fixes https://github.com/uProxy/uproxy/issues/736
also clean up notification text
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/934)
=> reject login promise so that it can be sent to the extension

src/chrome/extension/scripts/chrome_browser_api.ts, src/chrome/extension/scripts/chrome_core_connector.ts
Ran grunt test. 
Addressing this: https://github.com/uProxy/uproxy/issues/907
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/915)
=> Add minimum wait time between trying to create popups

src/generic_core/remote-connection.ts, src/generic_core/remote-instance.ts, src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/copypaste.ts, src/generic_ui/scripts/ui.ts
Fixes #950
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/953)
=> Fix some usability issues for copypaste

Gruntfile.coffee, src/chrome/extension/scripts/chrome_core_connector.ts, src/generic_core/core.ts, src/generic_core/remote-instance.spec.ts, src/generic_core/remote-instance.ts, src/generic_core/social.spec.ts, src/generic_core/social.ts, src/generic_core/user.spec.ts, src/generic_core/user.ts
create user object and put it in roster before storage read finishes.
add onceLoaded promises to user and remote instance classes
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/923)
=> async storage reads

src/generic_core/freedom-module.json, src/uproxy.ts
Cleanup Command enum.
Tested in Chrome and using grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/966)
=> Cleanup Command enum

src/generic_core/user.ts
fixes #864 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/978)
=> notify ui after receiving updated instanceId -> clientId mapping

src/generic_ui/polymer/description.html, src/generic_ui/polymer/description.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/989)
=> update description in ui

src/generic_core/util.spec.ts, src/generic_core/util.ts
Tested by running grunt test (and acking the code base for all function names)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1020)
=> Remove unused functions from util.ts

Gruntfile.coffee
Ran grunt test.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1054)
=> Fix Firefox UI broken by changed grunt rules.

src/chrome/extension/scripts/chrome_browser_api.ts, src/chrome/extension/scripts/chrome_core_connector.spec.ts, src/firefox/data/scripts/firefox_browser_api.ts, src/generic_ui/polymer/instance.ts, src/generic_ui/scripts/ui.spec.ts, src/generic_ui/scripts/ui.ts, src/interfaces/browser-api.d.ts, src/uproxy.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1041)
=> move notifications to browserApi

Gruntfile.coffee
Fixes #1067 
Tested by running uProxy in Firefox and running `grunt test`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1068)
=> Add any files in /generic to the firefox core build

src/generic_core/core.ts, src/generic_core/local-instance.ts, src/generic_core/social.ts, src/generic_core/user.ts, src/interfaces/network.d.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1063)
=> include everything in intial state

src/generic_ui/polymer/roster.html
Fixes https://github.com/uProxy/uproxy/issues/546
Tested in Chrome
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1073)
=> Rename invitation categories

src/generic_core/core.ts, src/generic_ui/polymer/feedback.ts, src/generic_ui/scripts/core_connector.ts, src/mocks/freedom-mocks.ts, src/uproxy.ts
Still todo: send logs to back end.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1080)
=> Allow user to see their app logs.

src/generic_core/core.ts, src/generic_ui/polymer/feedback.ts, src/generic_ui/scripts/core_connector.ts
Requires changes to website which are in a separate pull request.
UI sends a "include logs" bit to the Core and Core sends logs to backend if appropriate.
Ran grunt test and tested manually.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1087)
=> Send logs to backend.

package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json
Update the version to 0.6.1 (matches webstore version)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1086)
=> Update the version to 0.6.1

src/firefox/data/scripts/firefox_browser_api.ts, src/firefox/lib/glue.js
Fixes #1055 
Tested by using Firefox and seeing notifications
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1079)
=> Re-add desktop notifications to Firefox

Gruntfile.coffee, src/generic_core/remote-connection.spec.ts, src/mocks/rtc-to-net.ts, src/mocks/socks-to-rtc.ts
This adds some (very basic) tests for the remote-connection class
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1074)
=> Add tests for remote-connection

src/firefox/lib/firefox_proxy_config.js
ran grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1102)
=> Update FF to use dynamic ports

src/generic_ui/polymer/feedback.ts, src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts
Fixes #1109
Tested by making fake dialogs that fully implement full functionality
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1112)
=> Dialog tweaks

src/generic_ui/faq.html, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/splash.html
Styled with Roboto for now, will update styling when we have a better idea of what the design should be.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1100)
=> Add local FAQ content.

src/generic_core/user.ts
tested manually and run grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1119)
=> only save user's with instances

bower.json, src/generic_ui/index.html, src/generic_ui/polymer/root.html, src/generic_ui/polymer/splash.html
Looks like this:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1123)
=> Update main toolbar styling

src/generic_ui/polymer/app-bar.html, src/generic_ui/polymer/app-bar.ts, src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/copypaste.ts, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/root.html
* Tweak app-bar for copypaste and feedback
* Add a polymer element to encapsulate it
* Tweak proxying status bar
Tested visually, approved by @zahoriea 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1116)
=> Minor UI Tweaks

src/generic_ui/polymer/bubble.ts, src/generic_ui/polymer/contact.html, src/generic_ui/polymer/root.html, src/generic_ui/polymer/roster.html, src/generic_ui/polymer/splash.html
tested manually.
one instance offline:
both instances offline:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1130)
=> Remove scrollbar, fix 'offline' style, add break before loading bar.

src/generic_ui/polymer/app-bar.html, src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/splash.html
Remove extra spaces in front of copy-paste messages that were
interfere ins with padding
Fix margins for app-bar elements
Fix centering for app-bar elements
Change font-weight for app-bar title
Fixes #1151
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1158)
=> Make some minor tweaks to header display

src/chrome/app/manifest.json, src/chrome/extension/manifest.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1152)
=> Update manifest.json to allow communication with uproxy via it's appspot URLs.

src/chrome/extension/scripts/chrome_browser_api.ts, src/firefox/data/scripts/firefox_browser_api.ts, src/firefox/lib/glue.js, src/generic_core/core.ts, src/generic_core/remote-instance.spec.ts, src/generic_core/remote-instance.ts, src/generic_core/social.spec.ts, src/generic_core/social.ts, src/generic_ui/polymer/contact.ts, src/generic_ui/polymer/instance.ts, src/generic_ui/polymer/network.ts, src/generic_ui/scripts/ui.ts, src/generic_ui/scripts/user.spec.ts, src/generic_ui/scripts/user.ts, src/interfaces/browser-api.d.ts, src/uproxy.ts
This makes our notifications clickable and moves the code for producing them out of `generic_core`
Fixes #898
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1156)
=> Add clickable notifications

src/generic_ui/polymer/copypaste.ts
More work on #1125
Fixes #1184
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1187)
=> Move more assignment of globals to polymer object out of global scope

src/firefox/lib/firefox_proxy_config.js
This switches the setting of Firefox proxy settings to be done through
nsIProtocolProxyService instead of manually setting them in preferences.
Fixes #1185
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1186)
=> Switch Firefox proxy settings to use nsIProtocolProxyService

src/generic_ui/polymer/contact.html
Fixes #1174
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1192)
=> Hide overflow on contact names

src/chrome/app/manifest.json, src/chrome/extension/manifest.json
This is now on the Web Store!
(It also looked like the Web Store version was already 0.6.2, so I skipped that here.)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1202)
=> Increase version to 0.6.4

src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/chrome/extension/scripts/chrome_browser_api.ts
Fixes: https://github.com/uProxy/uproxy/issues/777 and https://github.com/uProxy/uproxy/issues/924
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1206)
=> Remove work-around for Chrome proxy settings bug.

src/firefox/lib/glue.js
This is the last piece for fixing: https://github.com/uProxy/uproxy/issues/531 (which was surprisingly nearly done).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1209)
=> Hide panel in Firefox after launching tab.

src/generic_ui/polymer/instance.ts, src/generic_ui/polymer/troubleshoot.html
Fixes #1211
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1217)
=> Minor tweaks to feedback/troubleshoot

src/generic_core/core.ts, src/generic_core/social.spec.ts, src/generic_core/social.ts, src/generic_ui/scripts/ui.ts, src/interfaces/persistent.d.ts, src/uproxy.ts
Fixes https://github.com/uProxy/uproxy/issues/1212
Tested in grunt test, Chrome, Firefox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1216)
=> Set version=1 on all messages and globalSettings

src/generic_ui/polymer/roster-group.html
Fixes #1219
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1221)
=> Use Roboto Medium for roster group headers

src/generic_ui/polymer/root.ts, src/generic_ui/scripts/ui.ts, src/uproxy.ts
Tested manually
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1222)
=> Simulate firing a core-signal from the background page.

src/generic_ui/polymer/roster.html, src/generic_ui/polymer/roster.ts, src/generic_ui/scripts/user.ts
Fixes #1127
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1220)
=> Clarify heading for trusted friends in get tab

src/generic_core/user.ts
Add url to UserState object to fix typescript error
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1239)
=> Add url to UserState object to fix typescript error

src/generic_ui/polymer/contact.html, src/generic_ui/polymer/contact.ts, src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/instance.html, src/generic_ui/polymer/instance.ts, src/generic_ui/polymer/splash.html
Fixes: https://github.com/uProxy/uproxy/issues/1189
Also resolves small issues discussed in person:
Signin page
- Change text below the title to "uProxy uses social networks to help you set up connections with your friends"
One-time connection page
- Chance all instances of "one time" to "one-time"
- Make the title sentence case
- More padding (based on spacing on the buddy list, and aligned to text box)
- Left align text
- Change submit feedback and "Request a one-time connection" to 18px
Get Access tab
- Change "Trying to get access" message to "Trying to connect"
- Replace "x has granted you access" with "Trying to get access from x" 
Updated splash:
Updated copypaste:
Submit feedback title size change: …
=> UI touch ups.

package.json, src/chrome/app/_locales/en/messages.json, src/chrome/app/manifest.json, src/chrome/extension/_locales/en/messages.json, src/chrome/extension/manifest.json
Once this is checked in, I'll merge to master!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1259)
=> Update version to 0.7.0. Change description to "Beta".

package.json
Update freedom-social-firebase version, to pick up fix for https://github.com/uProxy/uproxy/issues/1273
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1293)
=> Update freedom-social-firebase version

src/generic_core/user.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1296)
=> treat ONLINE_WITH_OTHER_APP as OFFLINE

src/generic_core/diagnose-nat.ts, src/generic_core/globals.ts, src/generic_ui/polymer/settings.ts
@salomegeo @iislucas @jpevarnek PTAL
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1315)
=> Add non-Google STUN servers to our list.

src/generic_ui/disconnected.html, src/generic_ui/polymer/faq-link.ts, src/generic_ui/scripts/ui.ts
Fixes #1336 
Tested by forcing pages to open in Chrome and Firefox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1351)
=> Fix urls (and internal paths) for browser pages

src/chrome/extension/scripts/background.ts, src/chrome/extension/scripts/chrome_browser_api.ts
This also renames trigger to emit for chrome_browser_api
Fixes #1343
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1355)
=> Fix scoping for chrome notifications event

Gruntfile.coffee, src/firefox/package.json
Firefox changes to package.json and Gruntfile to build xpi
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1354)
=> Firefox changes to package.json and Gruntfile to build xpi

src/generic_ui/scripts/ui.ts, src/generic_ui/scripts/user.ts
This also renames the UI variable in user to user_interface (in line
with the rest of the files)
Fixes #1337 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1371)
=> Get rid of the UI module, fix the path for DEFAULT_USER_IMAGE

src/generic_ui/faq.html
Taken from website
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1380)
=> Update local FAQ to include info about metrics.

src/generic_ui/polymer/root.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1394)
=> Change to the official bugzilla short URL

src/generic_ui/polymer/root.html, src/generic_ui/polymer/roster.html
Addressing: https://github.com/uProxy/uproxy/issues/1410 and https://github.com/uProxy/uproxy/issues/1386 and https://github.com/uProxy/uproxy/issues/1413
chrome
firefox
@zahoriea is the styling for the invite text ok?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1415)
=> Change roster title, 'beta' to 'alpha' and add invite text.

src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
Fixes this error:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1411)
=> Remove -dev from manifests

package.json
Change package for freedom-social-firebase
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1427)
=> Change package for freedom-social-firebase

Gruntfile.coffee, src/chrome/extension/scripts/context.ts, src/generic_ui/polymer/contact.ts, src/generic_ui/polymer/context.d.ts, src/generic_ui/polymer/copypaste.ts, src/generic_ui/polymer/description.ts, src/generic_ui/polymer/faq-link.ts, src/generic_ui/polymer/feedback.ts, src/generic_ui/polymer/instance.ts, src/generic_ui/polymer/network.ts, src/generic_ui/polymer/reconnect.ts, src/generic_ui/polymer/root.ts, src/generic_ui/polymer/roster.ts, src/generic_ui/polymer/settings.ts, src/generic_ui/polymer/splash.ts, src/generic_ui/polymer/troubleshoot.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1381)
=> Rename browserified_exports for the UI to ui_context

src/generic_ui/polymer/root.ts, src/generic_ui/scripts/ui.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1436)
=> Update Firefox version check now that FF38 has been fixed.

package.json, src/generic_core/remote-connection.ts
Fixes:
https://github.com/uProxy/uproxy/issues/1320
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1443)
=> log the SOCKS proxy address

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1457)
=> Add setup.sh step to "Building uProxy" section. Needed post-requireify.

README.md
Another small README fix.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1461)
=> Fix build/dev paths in README.

src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
(Note: package.json had already been updated.)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1471)
=> updated version numbers

src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1472)
=> Merge dev to make our release candidate. 

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
Now release-candidate had 0.8.5, time to update dev to 0.8.6.  
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1475)
=> update dev version to 0.8.6

Gruntfile.coffee, src/integration/core.spec.ts, src/integration/gtalk_credentials.ts, src/integration/integration.json, src/integration/mock_oauth.ts, src/integration/oauth_view_mock.ts, src/integration/test_connection.ts
grunt integration_test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1466)
=> requirify integration test

Gruntfile.coffee
This cuts down on package sizes by a decent chunk by only copying the
files we need.
Building the Firefox xpi is now done in the dist task.
Fixes #1384
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1465)
=> Add a dist rule

src/chrome/app/scripts/main.core-env.ts
fix #1387.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1487)
=> use workers

src/generic_core/metrics.ts, src/generic_core/remote-instance.spec.ts
Fix metrics .d.ts and test
Tested in Chrome, Firefox, grunt test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1515)
=> Fix metrics .d.ts and test

Gruntfile.coffee
Add metrics to dist rule
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1518)
=> Add metrics to dist rule

Gruntfile.coffee, src/chrome/extension/scripts/background.ts
Make sure we include .js files that are needed for individual pages as
well as the copypaste.html page for chrome.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1520)
=> Fix some dist issues

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1522)
=> Bump version #s to 0.8.7

Gruntfile.coffee, README.md
And add integration_test to 'everything'
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1531)
=> add integration test instructions to README

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1554)
=> Bump version numbers to 0.8.8

src/generic_ui/polymer/contact.ts, src/generic_ui/polymer/root.html, src/generic_ui/polymer/roster-group.html, src/generic_ui/polymer/roster-group.ts, src/generic_ui/polymer/roster.html, src/generic_ui/scripts/ui.spec.ts, src/generic_ui/scripts/ui.ts, src/generic_ui/scripts/user.ts
Summary of commits:
* Make user.isOnline public
* Sort contacts based on whether getting/giving access to them
* Render contacts from sorted array
* Each contact emits an event when it changes
* No longer split contacts by online/offline in the model
See commit messages for much more detailed information
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1489)
=> Sort contacts based on whether getting/giving access to them

src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/roster.html, src/generic_ui/style/global.css
Colour cleared with Izzie
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1587)
=> Add a default style for links

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
Update version for release.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1582)
=> Bump version to 0.8.9

Gruntfile.coffee, bower.json, src/generic_ui/polymer/settings.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1589)
=> Merge patches for v0.8.8 release back into dev.

src/generic_core/remote-instance.ts
a.k.a. for current clients to get access from newer clients
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1601)
=> fix for non-bridge clients to get access from bridge clients

package.json
We are having issues with typescript version changes in minor version
bumps.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1616)
=> Change request version for grunt-ts to ~4.1.0

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1622)
=> Bump version numbers to 0.8.11

src/generic_ui/polymer/settings.ts
Yeah, so, I really have no explanation for this one...
Let's say I was trying to create as many bugs as possible in the fewest lines of code.  Yeah.  That's it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1626)
=> Fix issues with displaying network names and counts

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
Update version #s to 0.8.12
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1642)
=> Update version #s to 0.8.12

src/generic_ui/polymer/settings.html
Before:
After:
Chrome:
Firefox:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1675)
=> Fix RTL connected accounts alignment.

src/generic_core/remote-user.ts
fixes #1649
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1656)
=> save offline facebook friends state

src/generic_core/globals.ts
Instead of doing a replacement of the settings object with whatever we
load from storage, merge the two objects together.  This simplifies the
process for adding new elements and removes duplication for where we set
default values.
Fixes #1653
Tested by restarting the app a bunch of times and making sure things were fine.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1682)
=> Use the default values from the settings object

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
Bump version for next release.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1679)
=> Bump version to 0.8.13

src/generic_ui/polymer/contact.html, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/root.html, src/generic_ui/polymer/splash.html
Tested visually in Chrome/Firefox.
Fixes: https://github.com/uProxy/uproxy/issues/1505
New screenshots:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1689)
=> UI polish.

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1697)
=> Update versions to 0.8.14

src/generic_core/diagnose-nat.ts
Unblocks freedomjs/freedom-for-firefox#68.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1700)
=> Changed bind() to use 0.0.0.0 in NAT diagnosis

src/generic_core/remote-connection.spec.ts, src/generic_core/remote-connection.ts, src/generic_core/remote-instance.ts
Fixes https://github.com/uProxy/uproxy/issues/1568
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1699)
=> Tell RtcToNet the user ID so it can enforce quotas.

src/generic_ui/locales/en/messages.json, src/generic_ui/scripts/translator.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1709)
=> Set English as translation fallback. Add missing string.

src/chrome/extension/scripts/background.ts, src/chrome/extension/scripts/chrome_tab_auth.ts, src/chrome/extension/scripts/context.ts, src/firefox/data/scripts/background.ts, src/generic_ui/scripts/ui.spec.ts, src/generic_ui/scripts/ui.ts, src/generic_ui/scripts/user.spec.ts
This changes the code for handling initial state messages so that we remove existing networks instead of just popping them from the array.  More details are in commit messages.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1714)
=> Fix handling initial state

src/generic_core/local-instance.ts, src/generic_core/remote-instance.spec.ts, src/generic_core/remote-instance.ts, src/generic_core/remote-user.spec.ts, src/generic_core/remote-user.ts, src/generic_core/social.spec.ts, src/generic_core/storage.ts, src/generic_core/uproxy_core.ts
This cleans up a few TODOs from `storage.ts` as well as removing some dead code.  The only functionality change here should be that we actually propagate errors when we intend to (and yes, this is my pitiful attempt to have gotten at least something productive done today).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1724)
=> Storage cleanup

src/firefox/data/scripts/background.ts
Verbal approval given by @dborkan
=> Fix bug with not exporting model in Firefox

package.json, src/generic_core/diagnose-nat.ts, src/mocks/rtc-to-net.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1732)
=> Pulling in fixes for testing release candidate for r0.8.14

src/generic_ui/scripts/ui.ts
The feedback type should be sent to our website as a string (an int is ambiguous).
Tested on Chrome
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1735)
=> Submit feedbackType as a string, not a number.

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1728)
=> Version number bump for release 8.14 (making dev now 8.15)

src/generic_core/firewall.spec.ts
#1734
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1738)
=> quick fix for test

src/generic_ui/scripts/ui.ts
This just fixes a small typo.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1750)
=> Fix message for sharing access with many friends

src/chrome/extension/polymer/app-missing.html, src/generic_ui/locales/ar/messages.json, src/generic_ui/locales/en/messages.json, src/generic_ui/locales/fa/messages.json, src/generic_ui/locales/tr/messages.json, src/generic_ui/locales/vi/messages.json, src/generic_ui/polymer/advanced-settings.html, src/generic_ui/polymer/bubble.html, src/generic_ui/polymer/contact.html, src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/copypaste.ts, src/generic_ui/polymer/description.html, src/generic_ui/polymer/description.ts, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/feedback.ts, src/generic_ui/polymer/instance.html, src/generic_ui/polymer/instance.ts, src/generic_ui/polymer/logs.html, src/generic_ui/polymer/network-in-settings.html, src/generic_ui/polymer/reconnect.html, src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts, src/generic_ui/polymer/roster.html, src/generic_ui/polymer/settings.html, src/generic_ui/polymer/settings.ts, src/generic_ui/polymer/splash.html, src/generic_ui/polymer/troubleshoot.html, src/generic_ui/polymer/troubleshoot.ts, src/generic_ui/scripts/ui.ts, src/generic_ui/scripts/user.ts
This is needed to follow guidelines for translation.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1762)
=> Change all i18n placeholders to uppercase constants.

src/generic_core/globals.ts
Fixes https://github.com/uProxy/uproxy/issues/1769
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1770)
=> Remove excess STUN servers.

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/advanced-settings.html, src/generic_ui/polymer/app-bar.html, src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/copypaste.ts, src/generic_ui/polymer/description.html, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/root.html, src/generic_ui/polymer/settings.html, src/generic_ui/scripts/ui.ts, src/generic_ui/style/global.css
This updates to copy+paste UI to use styles from the new mocks
Fixes #1743
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1753)
=> Cleanup copy+paste UI

src/generic_ui/polymer/copypaste.html
This is just style cleanup from me not being thorough before.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1773)
=> Fix some css rules in copy+paste

src/chrome/extension/scripts/chrome_browser_api.ts, src/firefox/lib/firefox_proxy_config.js, src/generic_core/firewall.spec.ts, src/generic_core/remote-instance.ts, src/generic_core/uproxy_core.ts, src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts, src/generic_ui/scripts/core_connector.ts, src/generic_ui/scripts/ui.spec.ts, src/generic_ui/scripts/ui.ts, src/interfaces/social.ts, src/interfaces/uproxy_core_api.ts
fixes #1638
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1704)
=> seamless switching and reconnect

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1778)
=> Update version to 0.8.16 (last week's version)

src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1780)
=> Updating firefox package.json version

removekey.py, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, version.py
Once merged, I'll update the release doc!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1771)
=> Scripts to bump version and remove keys from chrome manifests.

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1782)
=> Update version to 0.8.17 for next week

src/generic_ui/polymer/advanced-settings.html, src/generic_ui/polymer/advanced-settings.ts
So, I kind of broke things...
This fixes some styling that was broken on Firefox as well as some validation that was broken overall.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1800)
=> Fix the advanced settings view and functionality

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json, version.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1826)
=> Update version to v0.8.19, +x version.py

Gruntfile.coffee
Fixes https://github.com/uProxy/uproxy/issues/1837
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1843)
=> Add PGP module to dist builds

src/chrome/extension/scripts/chrome_core_connector.spec.ts, src/generic_core/freedom-module.ts, src/generic_core/social.ts, src/generic_core/stored_value.ts, src/generic_core/uproxy_core.ts, src/generic_ui/scripts/core_connector.ts, src/generic_ui/scripts/ui.ts, third_party/tsd.json
See individual commit messages for more details.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1819)
=> Add reconnect on startup/update

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1846)
=> Update version numbers to 0.8.20

src/generic_ui/scripts/ui.ts
Fixes #1864
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1866)
=> Fix error with being disconnected from a one-time-connection

src/generic_ui/polymer/copypaste.html, src/generic_ui/polymer/copypaste.ts
Done based on UX suggestions
Fixes #1528
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1854)
=> Always allow the user to navigate back from copy+paste

package.json, src/cca/app/scripts/main.core-env.ts, src/chrome/app/scripts/chrome_ui_connector.ts, src/chrome/app/scripts/main.core-env.ts, src/generic_core/firewall.spec.ts, src/generic_core/firewall.ts, src/generic_core/freedom-module.ts, src/generic_core/globals.ts, src/generic_core/remote-connection.ts, src/generic_core/remote-instance.spec.ts, src/generic_core/remote-instance.ts, src/generic_core/remote-user.ts, src/generic_core/social.spec.ts, src/generic_core/social.ts, src/generic_core/storage.ts, src/generic_core/ui_connector.ts, src/generic_core/uproxy_core.ts, src/generic_ui/scripts/user.ts, src/integration/core.spec.ts, src/interfaces/uproxy_core_api.ts, src/mocks/freedom-mocks.ts, third_party/tsd.json
They add a bit more type safety and also do not need to be copied in
from other repositories!
DO NOT MERGE THIS UNTIL `uproxy-libv31` ACTUALLY EXISTS
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1870)
=> Start using the new freedom typings from DefinitelyTyped

src/cca/app/scripts/cordova_core_connector.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1876)
=> Fix a typing issue for the cca connector

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1879)
=> Bump version to 0.8.22

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/contact.html
Tested on Chrome and FF.
Resolving: https://github.com/uProxy/uproxy/issues/874
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1888)
=> Show "Online" or "Offline" below user.

src/generic_ui/polymer/copypaste.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1892)
=> Always start a new getting session when switching in copy+paste

src/generic_ui/polymer/contact.html, src/generic_ui/polymer/contact.ts
Before, when the contact was collapsed, the contact name was slightly above center. When expanded, it was exactly centered (vertically). This meant the name jumped up and down a little. 
This fixes it by keeping the contact name in its slightly above center position even when expanded.
Before:
After:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1889)
=> Move core-collapse inside the name row so it can fit better under the contact name.

src/generic_ui/faq.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1893)
=> Update local FAQ.

src/generic_ui/polymer/contact.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1896)
=> Fix bad contact closing behavior.

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
Update version #s to 0.8.23
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1897)
=> Update version #s to 0.8.23

Gruntfile.coffee, package.json, src/chrome/app/manifest.json, src/generic_core/dev_build/freedom-module.json, src/generic_core/dist_build/freedom-module.json, src/generic_core/social.ts, src/generic_ui/polymer/network.html
Integrating wechat into uproxy as a social provider.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1891)
=> Spencer wechat

src/generic_ui/locales/ar/messages.json, src/generic_ui/locales/en/messages.json, src/generic_ui/locales/fa/messages.json, src/generic_ui/locales/tr/messages.json, src/generic_ui/locales/vi/messages.json, src/generic_ui/polymer/bubble.html, src/generic_ui/polymer/network.ts, src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts, src/generic_ui/polymer/roster.html, src/generic_ui/polymer/splash.html
Merge Lucy's UI changes for friend invites and metrics opt-in
This includes most changes from https://github.com/uProxy/uproxy/pull/1871, and fixes a bug in how view updates had been done
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1913)
=> Merge Lucy's UI changes for friend invites and metrics opt-in

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/invite-user.ts
New invite email format from https://docs.google.com/document/d/1QoeDRPNy66h0yJrrBeqJSZArW7nMhbWBDX_yRP6BiUY/edit
Requires changes from https://github.com/freedomjs/freedom-social-firebase/pull/37
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1917)
=> New invite email format

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/accept-user-invite.html, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/invite-user.html, src/generic_ui/polymer/root.html, src/generic_ui/polymer/roster.html
Updated styling and help text for invites
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1922)
=> UX updates for invites

src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts
Fixes: https://github.com/uProxy/uproxy/issues/1919
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1927)
=> Update FAB position if status bar is visible.

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
Update version to 0.8.24
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1936)
=> Update version to 0.8.24

README.md
Give better instructions for using Git, setting PATH variables and "installing globally" for Windows.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1956)
=> README updates for Windows

src/generic_ui/polymer/contact.html
Issue that has been fixed: https://github.com/uProxy/uproxy/issues/1688
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1965)
=> Removed has granted access text

src/generic_ui/polymer/avatar.html, src/generic_ui/scripts/constants.ts, src/generic_ui/scripts/user.ts
Fixes #1935
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1941)
=> Use the default avatar everywhere

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/contact.html
Couple cleanup tasks related to #1688
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1971)
=> Clean up some code related to unnecessary text for getting/sharing indication

src/generic_ui/locales/en/messages.json, src/generic_ui/scripts/ui.ts
https://github.com/uProxy/uproxy/issues/850
With @huma-hamid
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1968)
=> Confirmation modal for log out button

.gitignore, Gruntfile.coffee, src/cca/app/scripts/context.ts, src/cca/app/scripts/cordova_browser_api.ts, third_party/typings/cordova/inappbrowser.d.ts
This change also adds the beginnings of getter support, and disables
Crosswalk (which appears to have a bug with CCA at the moment).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1994)
=> Rescue cordova build from several bugs and changes in Cordova/CCA.

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2007)
=> Bump versions

src/generic_ui/scripts/ui.spec.ts, src/generic_ui/scripts/ui.ts
Okay, so, I started working on cleaning up code for logging out.  Full disclaimer form that commit copied here:
> Okay, this is my personal take on the best style we could use for this
> function.
> 
> Things I was optimizing for:
> * absolutely no duplicated code
> * remove indentation creep
> 
> A good part of this is me imposing my personal style preferences, so,
> whoever is looking at the PR, let's actually chat about individual
> preference?
Anyways, I ended up splitting out a bit more and even adding a test (gasp!)
To reiterate a bit, please comment on personal preference stuff.  This PR is almost entirely me imposing my preference on the code, I'd like to hear opinions more than facts. …
=> Cleanup of some functionality

src/generic_core/firewall.ts, src/generic_core/freedom-module.ts, src/generic_core/globals.ts, src/generic_core/local-instance.ts, src/generic_core/remote-connection.ts, src/generic_core/remote-instance.ts, src/generic_core/remote-user.ts, src/generic_core/social.ts, src/generic_core/ui_connector.ts, src/generic_core/uproxy_core.ts
All imports are now alphabetized by filename.
Fixes #1816
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1987)
=> Clean up imports in generic_core

src/generic_ui/polymer/advanced-settings.html, src/generic_ui/polymer/advanced-settings.ts, src/generic_ui/polymer/faq-link.html, src/generic_ui/polymer/faq-link.ts, src/generic_ui/polymer/faq.ts, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/feedback.ts, src/generic_ui/polymer/root.html, src/generic_ui/polymer/roster.html, src/generic_ui/polymer/roster.ts, src/generic_ui/polymer/settings.html, src/generic_ui/polymer/settings.ts, src/generic_ui/polymer/splash.html, src/generic_ui/polymer/splash.ts, src/generic_ui/polymer/troubleshoot.html, src/generic_ui/polymer/troubleshoot.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2019)
=> Readd uproxy-faq-link, use for links to the faq

src/generic_core/remote-instance.spec.ts, src/generic_core/remote-instance.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2020)
=> remove dependency on message version

src/generic_ui/polymer/faq.html, src/generic_ui/polymer/faq.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2024)
=> Fix FAQ css, add anchors for different questions and scroll to them appropriately

src/generic_ui/polymer/contact.html, src/generic_ui/polymer/contact.ts, src/generic_ui/polymer/instance.html, src/generic_ui/polymer/instance.ts, src/generic_ui/polymer/roster-group.ts
Stealing this one from the GHC list since no one tackled it there, it's far too annoying and deals too much with Polymer internals (in my opinion) to be used as an onboarding bug, and I really just missed boring bugfixing :)
Sorry about the hackiness...
See commit messages.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1991)
=> Sort instances by whether or not they are online

src/generic_ui/polymer/faq.html, src/generic_ui/polymer/root.html
tested manually
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2025)
=> Fix faqs link on anonymous metrics welcome page

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/feedback.html, src/generic_ui/polymer/feedback.ts
https://github.com/uProxy/uproxy/issues/1375?_pjax=%23js-repo-pjax-container
fix for bug linked above
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/1967)
=> Updated to validate feedback is not empty.

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2029)
=> Bump version to 0.8.27

src/generic_core/dev_build/freedom-module.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2032)
=> Update WeChat social provider to use the social2 API

package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2077)
=> migrate to latest uproxy-lib, with latest cloud provider

bower.json, src/generic_ui/polymer/accept-user-invite.ts
Fixes: https://github.com/uProxy/uproxy/issues/2076
The core-overlay problem was discussed here: https://github.com/Polymer/core-overlay/issues/37 and I saw someone had created a patch. I forked that, published it, and now bower uses that instead of the stock core-overlay code. I think this should fix our core-overlay problem forever (forever!)
Also, @trevj caught that we couldn't add multiple cloud friends. This was happening because I tried to login each time we entered a cloud invite. I fixed that, but we still see the confirmation ("you've entered an experimental code...") each time. I left that in because I thought it might be helpful, but it's easy to take out if that's better. …
=> Fix core-overlay freezing. Allow users to add multiple Cloud friends.

Gruntfile.coffee, package.json
Fixes #2033
(as an extra thing)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2083)
=> Fix the third party data to copy for Firefox

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/accept-user-invite.ts, src/generic_ui/polymer/feedback.ts, src/generic_ui/polymer/invite-user.ts, src/generic_ui/polymer/network-invite-user.ts, src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts, src/generic_ui/scripts/ui.ts, src/interfaces/ui.ts
* Enforce that Quiver user name is not empty
* cleanup open-dialog code (all 'open-dialog' calls that only used 1 button now invoke ui.showDialog)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2098)
=> Enforce that Quiver user name is not empty, cleanup open-dialog code

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2092)
=> Add instructions for the Android build

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2103)
=> Merge release back into dev

package.json, src/generic_core/firewall.ts, src/generic_core/social.spec.ts, src/generic_core/social.ts, src/interfaces/social.ts, src/interfaces/social2.ts
Use Quiver w/ domain fronting, rename inviteUserData to inviteResponse
Tested in Chrome and Firefox
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2109)
=> Use Quiver w/ domain fronting, rename inviteUserData to inviteResponse

src/generic_ui/polymer/invite-user.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2119)
=> Clear the inputs when opening invite-user

src/generic_ui/polymer/contact.html, src/generic_ui/scripts/ui.ts
FF:
Tested in Chrome & FF
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2124)
=> Expand new Github friend requests. Make pending friends look active.

src/cca/app/manifest.json, src/cca/app/scripts/cordova_browser_api.ts, src/chrome/extension/scripts/chrome_browser_api.ts, src/firefox/data/scripts/firefox_browser_api.ts, src/generic_ui/scripts/ui.spec.ts, src/generic_ui/scripts/ui.ts, src/interfaces/browser_api.ts, third_party/typings/chrome/chrome-app.d.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2130)
=> Abdalkader wifi notification

src/cca/app/manifest.json, src/cca/app/scripts/cordova_browser_api.ts, src/chrome/extension/scripts/chrome_browser_api.ts, src/firefox/data/scripts/firefox_browser_api.ts, src/generic_ui/scripts/ui.spec.ts, src/generic_ui/scripts/ui.ts, src/interfaces/browser_api.ts, third_party/typings/chrome/chrome-app.d.ts
Reverts uProxy/uproxy#2130
I merged this accidentally :(
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2131)
=> Revert "Abdalkader wifi notification"

src/generic_core/dist_build/freedom-module.json
Add GitHub to the dist build - it's really happening!!!
Tested in Chrome and FF dist builds
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2137)
=> Add GitHub to the dist build

src/generic_core/globals.ts, src/generic_core/uproxy_core.ts, src/generic_ui/polymer/splash.ts, src/generic_ui/scripts/ui.ts, src/integration/core.spec.ts, src/interfaces/uproxy_core_api.ts
Also cleans up the settings update handler.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2146)
=> Add new field in settings for having seen the metrics opt-in

src/generic_ui/polymer/invite-user.ts, src/generic_ui/polymer/login-common.ts, src/generic_ui/polymer/splash.html, src/generic_ui/polymer/splash.ts
There was some code duplication between invite-user and the splash
screen, this removes the duplication that I was able to find.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2145)
=> Move some of the common login functionality to a common location

scraps/release.sh
This script should handle most of what we want to do in a normal release
cycle.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2149)
=> Add a very simple release script

CONTRIBUTING.md
use template from http://todogroup.org/opencodeofconduct/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2152)
=> add code of conduct

package.json
For:
https://github.com/uProxy/uproxy/pull/2159
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2169)
=> upgrade uproxy-lib for new cloud invite fixes and additions

Gruntfile.coffee
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2172)
=> Switch to using buildAndRunTest from uproxy-lib

Gruntfile.coffee, package.json, src/firefox/lib/glue.js, src/firefox/lib/main.js, src/firefox/package.json
Get jpm working for Firefox dev build without breaking dist build
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2195)
=> Get jpm working for Firefox dev build without breaking dist build

src/generic_core/firewall.ts
Remove duplicate timestamp check in firewall.ts
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2219)
=> Remove duplicate timestamp check in firewall.ts

src/generic_ui/polymer/faq.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2232)
=> Remove Quiver FAQ until we are ready for webstore

src/generic_core/metrics.ts
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2254)
=> Remove unnecessary check that breaks firefox.

scraps/release.sh
Updates for having moved to github flow:
- build `master`
- no pushes/pulls from `release` or `release-candidate`
I just used it to create this pull request:
https://github.com/uProxy/uproxy/pull/2242
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2243)
=> update release.sh for github flow

Gruntfile.coffee
This removes a lot of the duplicated rules in the Gruntfile and tries to structure them in a more logical way
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2238)
=> Simplify grunt again

src/generic_ui/scripts/ui.ts
Fix jdenticons for Firefox
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2255)
=> Fix jdenticons for Firefox

Gruntfile.coffee, package.json, src/generic_core/dist_build/freedom-module.json, src/generic_ui/polymer/faq.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2259)
=> Add Quiver to uProxy dist build!!

package.json
Watch and be amazed as shippable tests pass for this pull request!
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2277)
=> Fix shippable tests

src/generic_ui/polymer/network-invite-user.html, src/generic_ui/polymer/network-invite-user.ts
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2284)
=> Remove unused cloud code from network-invite-user

Gruntfile.coffee, package.json, src/generic_core/dev_build/freedom-module.json, src/generic_core/freedom-module.ts, src/generic_core/uproxy_core.ts, src/generic_ui/polymer/cloud-install.html, src/generic_ui/polymer/cloud-install.ts, src/generic_ui/polymer/invite-user.html, src/generic_ui/polymer/invite-user.ts, src/generic_ui/scripts/core_connector.ts, src/generic_ui/scripts/model.ts, src/generic_ui/scripts/ui.ts, src/interfaces/uproxy_core_api.ts
This adds a button to the "connect with a friend" screen which helps you create a cloud server. When clicked, it:
* prompts you to log into your DigitalOcean account
* creates a server, using your DigitalOcean account
* SSHes into the new server and runs the install script
* shows the invitation URL for the new server
This is very much MVP. Several issues:
* oftentimes, the new server cannot be SSHed into for several seconds (clicking the new button again will resume the install) https://github.com/uProxy/uproxy/issues/2190
* the new server should be added to the roster
* needs a much better success dialog (right now it's just a toast)
* error handling throughout isn't great
For the dev build, only. @lucyhe: would appreciate your input here too.
[<img …
=> create a cloud server workflow

src/chrome/app/scripts/chrome_ui_connector.ts, src/chrome/app/scripts/main.core-env.ts, src/chrome/extension/scripts/chrome_browser_api.ts, src/generic_core/freedom-module.ts, src/generic_core/uproxy_core.ts, src/interfaces/uproxy_core_api.ts, third_party/tsd.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2302)
=> Add skeleton for handling chrome policy

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2306)
=> upgrade uproxy-lib, for cloud fixes

src/generic_ui/polymer/invite-user.ts, src/generic_ui/polymer/network-invite-user.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2316)
=> Fixed UI not popping up, and minor nits

src/generic_ui/locales/en/messages.json, src/generic_ui/scripts/ui.ts
FYI, @lucyhe - hope I didn't forget something!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2323)
=> remove confirmation for accepting cloud invites

src/generic_ui/polymer/cloud-install.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2325)
=> fix typo on SIGN_ME_IN element

src/generic_core/uproxy_core.ts, src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/cloud-install.html, src/generic_ui/scripts/ui.ts, src/interfaces/uproxy_core_api.ts
Depends on:
* https://github.com/uProxy/uproxy-lib/pull/372
* https://github.com/uProxy/uproxy-docker/pull/74
In short, the "create server" phase takes 20% of the "time" - installation the rest. Installation is divided into several stages, defined in the install scripts (pull request above); roughly, the time is divided 50/50 between SSH and Zork image building.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2327)
=> fine-grained, translatable updates for cloud install

src/generic_core/uproxy_core.ts
TBR @dborkan. My bad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2329)
=> FIX: cloud install failure promise chain

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/faq.html
Adding in the newest Cloud questions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2324)
=> Update FAQ with Cloud content.

src/generic_ui/locales/en/messages.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2331)
=> Edits for Cloud FAQ entries.

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/cloud-install.html, src/generic_ui/polymer/cloud-install.ts
Add FAQ links ("learn more", etc) to cloud deployment screens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2330)
=> Add FAQ links to cloud deployment screens

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/cloud-install.html
@gwpenn's suggestions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2335)
=> bold the "stay online" cloud install warning

Gruntfile.coffee, src/generic_core/dist_build/freedom-module.json
It's time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2336)
=> enable cloud in dist build

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/cloud-install.ts
Use our referral link, plus some wording changes from UX.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2339)
=> use our referral link for DigitalOcean signup button

src/generic_core/social.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2351)
=> Quick fix for cloud invites not working

src/generic_ui/scripts/translator.ts
Fixes broken translations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2378)
=> Re-add in language resources (deleted by accident).

src/generic_ui/polymer/cloud-install.html, src/generic_ui/polymer/root.html, src/icons/plus_white.svg
Miscellaneous UI improvements (thanks @ohnocassio!):
- improved + icon in fab
- position + icon in center of fab
- reduce space between "Create new account" and "I have an account" buttons
for cloud
Tested in Chrome and FF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2383)
=> misc. UI improvements

src/generic_core/social.ts
closes #2385
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2390)
=> use v2 invite link for cloud server SHARE WITH A FRIEND

src/generic_ui/polymer/cloud-install.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2416)
=> use DigitalOcean's dedicated sign up page during cloud setup (closes #2415)

Gruntfile.coffee
I have verified that this change has no effect on the resulting
build file tree.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2421)
=> Reduce duplication of filenames in the dist build

src/cca/app/scripts/cordova_browser_api.ts, src/chrome/extension/scripts/background.ts, src/firefox/lib/url-handler.js, src/generic_ui/polymer/network-invite-user.ts
This improves the UX on desktop, and is important on mobile because the invite dialog blocks the entire UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2422)
=> Autoclose facebook message sending tab

src/generic_ui/polymer/cloud-install.html, src/generic_ui/polymer/cloud-install.ts, src/generic_ui/scripts/ui.ts
Since the cloud social provider no longer does any real work when adding a friend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2428)
=> cloud install cancel polish and fixes

src/generic_ui/polymer/contact.ts, src/generic_ui/scripts/user.ts
Also fixes some issues with the delete button.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2430)
=> Ensure share contact expands for cloud

src/cca/app/scripts/context.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2431)
=> Add a hacky workaround to force UI refreshes on Android.

src/generic_ui/scripts/model.ts
Good guess, @dborkan:
https://github.com/uProxy/uproxy/issues/2191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2432)
=> FIX: cloud friends in SHARE ACCESS tab multiply on app reload

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/cloud-install.html, src/generic_ui/polymer/cloud-install.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2434)
=> Switch to using a checkbox for whether to include a refcode

src/chrome/extension/scripts/background.ts, src/firefox/lib/glue.js, src/generic_core/globals.ts, src/generic_ui/polymer/cloud-install.ts, src/generic_ui/polymer/network-invite-user.ts, src/generic_ui/scripts/model.ts, src/generic_ui/scripts/ui.ts, src/interfaces/uproxy_core_api.ts
This accompanies uProxy/uproxy-website#146.
If this looks good, next we can add a checkbox to the UI that allows the user to override the promo auto-detection we do here as per @gwpenn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2429)
=> check for OFF promo, don't use DO referral code if found

src/firefox/lib/glue.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2436)
=> rm stray merge conflict indicator

src/interfaces/uproxy_core_api.ts
The dictionary key is the IP address, and the dictionary value is the public key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2444)
=> Changing Valid Proxy Server Dictionary Format

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2456)
=> minor updates to package.json

Gruntfile.coffee
Oops, forgot to add `samples` to `build`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2467)
=> some more dist fixes

bower.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
TBR @jpevarnek 
Seems like all these should have been updated, too:
https://github.com/uProxy/uproxy/pull/2468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2472)
=> update version to 0.9.0 throughout

README.md
This shortens the README file and makes it easier to navigate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2484)
=> Move Mobile-development info to Wiki

src/generic_ui/polymer/faq.ts
Fixes #2269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2492)
=> Scroll to top of FAQ when opened

src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts
fixing issue https://github.com/uProxy/uproxy/issues/2382
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2491)
=> Added button to quiver popup

Gruntfile.coffee
Gah, I keep missing these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2496)
=> remove references to uproxy-obfuscators

Gruntfile.coffee, src/lib/samples/echo-server-node/index.js
As discussed, this is to help us diagnose Simple SOCKS issues: the problem is that no data sent by the server is ever received!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2493)
=> echo server sample app for node

src/generic_ui/polymer/state.ts
Fixes #2510
First try at using the web interface for Github, this is fun!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2511)
=> Fix missing call to doInBackground_

src/chrome/extension/scripts/context.ts, src/firefox/data/scripts/background.ts, src/generic_ui/polymer/settings.html, src/generic_ui/polymer/settings.ts, src/generic_ui/scripts/ui.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2486)
=> Remove browser property from ui, check for window.chrome instead

src/generic_ui/polymer/cloud-install.ts, src/generic_ui/polymer/contact.ts, src/generic_ui/polymer/instance.ts, src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts, src/generic_ui/scripts/background_ui.ts, src/generic_ui/scripts/ui.ts
This switches the process of showing a toast message in the UI to be
done based on a core-signal being fired instead of based on variables
changing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2490)
=> Use message passing for showing toast objects

src/generic_ui/polymer/root.ts, src/generic_ui/polymer/settings.html
Fixes issue #2273  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2520)
=> Fixed description field so it cancels when settings pane is closed

src/generic_ui/polymer/contact.html, src/generic_ui/polymer/root.html
Fixes #2272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2517)
=> Fixed the cursor for adding friends on github.

src/lib/build-tools/alias/randombytes.js
We got some reports of issues accessing cloud servers from Firefox:
https://github.com/uProxy/uproxy/issues/2545
The issue seems to be the randombytes shim; this fixes a few issues from https://github.com/uProxy/uproxy-lib/pull/405.
More testing required in future!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2551)
=> scoping and API fixes for randombytes buffering, for firefox <48

src/generic_ui/polymer/root.ts
Apparently I forgot that with a change a while ago, now corrected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2562)
=> Finish killing signalToFire

src/lib/build-tools/alias/randombytes.js
Damn!
Followup to:
https://github.com/uProxy/uproxy/pull/2551
FYI, @jab
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2563)
=> FIX randombytes crash when core.crypto unavailable, extra debug logging

src/cca/app/manifest.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2574)
=> Bump android version to 0.0.2

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/feedback.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2572)
=> Fixes issue #2570

src/generic_core/freedom-module.ts, src/generic_core/uproxy_core.ts, src/generic_ui/polymer/advanced-settings.html, src/generic_ui/polymer/advanced-settings.ts, src/generic_ui/scripts/core_connector.ts, src/generic_ui/scripts/ui.ts, src/interfaces/uproxy_core_api.ts
Not relying on state sharing here gets us a bit closer to upgrading to Polymer 1.0 (#1900)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2550)
=> Better port control checking

src/generic_ui/locales/en/messages.json, src/generic_ui/polymer/root.html, src/generic_ui/polymer/root.ts
clicking on yes opens with this feedback form prefilled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2584)
=> New popup after connection between friends is broken that asks user to submit feedback

src/generic_ui/polymer/cloud-install.html, src/generic_ui/polymer/cloud-install.ts, src/generic_ui/scripts/translator.ts, src/generic_ui/scripts/ui.ts
Not relying on state-sharing here gets us a bit closer to the Polymer 1.0 upgrade (#1900)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2552)
=> Cloud install status in element

.travis.yml, Gruntfile.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2593)
=> do not rebuild just to run unit tests on travis

src/generic_ui/polymer/logs.ts
Fixes #2541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2601)
=> Update logs when when logs.html is called

src/generic_core/cca_dist_build/freedom-module.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2614)
=> Make the Android dist build Quiver + Cloud only

Gruntfile.coffee
Fixes issue #2617.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2623)
=> Fix cca.js getting suck on user input the first time building android

src/generic_ui/polymer/invite-user.ts
Fixes #2507 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2641)
=> Changed Friend Added dialog to a toast

package.json
This fixes the "function not found" error.
Sorry for the breakage :disappointed:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2661)
=> Revert xregexp upgrade

src/generic_core/freedom-module.ts, src/generic_core/globals.ts, src/generic_core/uproxy_core.ts, src/generic_ui/polymer/cloud-install.html, src/generic_ui/polymer/cloud-install.ts, src/generic_ui/polymer/description.html, src/generic_ui/polymer/description.ts, src/generic_ui/polymer/root.ts, src/generic_ui/polymer/settings.ts, src/generic_ui/polymer/splash.html, src/generic_ui/polymer/splash.ts, src/generic_ui/polymer/state.ts, src/generic_ui/scripts/background_ui.ts, src/generic_ui/scripts/core_connector.ts, src/generic_ui/scripts/model.ts, src/generic_ui/scripts/ui.ts, src/interfaces/uproxy_core_api.ts
Yeah, I'm sorry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2667)
=> Fix updates to globalSettings from Chrome Policy

Gruntfile.coffee
This removes the build/src/android directory from typescript module/core compilation (shouldn't be necessary) and also fixes the paths for the clean command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2669)
=> Fix a few android-related build issues

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2699)
=> bump version numbers

src/metrics/README.md, src/metrics/metrics_server/server.ts, src/metrics/metrics_server/use_service.ts, src/metrics/package.json, src/metrics/typings.json
* Use HTTP POST for recording metrics
* Use body-parser library to set req.body
* Updated readme instructions for curl
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2702)
=> Use HTTP POST for recording metrics

Gruntfile.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2709)
=> Update cordova-plugin-tun2socks endpoint

Gruntfile.coffee
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2712)
=> Remove Android dependency on cordova-plugin-device

src/generic_ui/polymer/app-bar.html
fixes #2660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2715)
=> increase back button hit area

src/generic_ui/polymer/app-bar.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2717)
=> make back button element a core-icon-button instead of core-icon

.gitignore, Gruntfile.coffee, package.json, src/generic_ui/scripts/translator.ts
Getting one step closer to simpler and incremental builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2719)
=> Compile Typescript straight to build/

Gruntfile.coffee
No one is using it yet, but it will fail without this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2721)
=> Fix watch task

src/cca/app/manifest.json
(Already pushed to play store.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2723)
=> Bump android version to 0.0.3 for this week's release

Gruntfile.js, package.json
This change makes sure tasks only run once, even if specified twice.
This significantly reduces the time to fully build. On the Travis run, the initial build goes from 1m 41s to 53s and the total Travis time goes from 6m 21s to 5m 25s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2732)
=> Run tasks only once

src/interfaces/uproxy_core_api.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2731)
=> Remove unused interface

src/cca/app/scripts/cordova_browser_api.ts
Fixes #2753 - along with [this tun2socks PR](https://github.com/uProxy/cordova-plugin-tun2socks/pull/10)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2754)
=> Update UI on VPN start failure

src/lib/cloud/digitalocean/provisioner.ts
This updates us to a new app which I promise not to accidentally delete.
I will roll this into a new uProxy release this morning.
=> update client id for new digitalocean api app

Gruntfile.js, replace_xwalk_in_apk.sh, src/cca/app/manifest.json
Fixes #2768 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2767)
=> Upgrade to Crosswalk 22

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2769)
=> Update link to Jasmine

src/generic_ui/locales/ar/messages.json, src/generic_ui/locales/zh_CN/messages.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2775)
=> Update translations with latest strings from vendor.

src/lib/integration-tests/socks-echo/base-spec.core-env.ts
@dborkan FYI
Workaround for https://github.com/uProxy/uproxy/issues/2757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2788)
=> disable tests which cause problems on osx

README.md
Visual Studio Code is so much easier to setup I wouldn't even mention Sublime; besides, IDE probably belongs in the wiki.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2795)
=> recommend visual studio code over sublime

Gruntfile.js
For those of us building zork for Node.js. FYI, @dborkan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2796)
=> fix freedom-for-node install step for yarn

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2799)
=> add visual studio code folder to list of files ignored by git

Gruntfile.js, src/lib/build-tools/common-grunt-rules.ts
Fixes:
https://github.com/uProxy/uproxy/issues/2729
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2805)
=> kill localLibsDestPath

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2804)
=> Bump version numbers to 0.9.11

.gitignore, Gruntfile.js, package.json, src/cca/bower.json, src/cca/index.html, src/cca/scripts/background.ts, src/cca/scripts/tun2socks_vpn_device.ts, src/cca/ui_components/server_list.ts
This is adding some basic support to reuse Polymer elements.
It's not great, but allows us to use the Material Design elements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2810)
=> Add basic Polymer support

src/cca/manifest.json
new features:
- polymer components
- save servers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2813)
=> bump android version number for release

Gruntfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2814)
=> pipe no into more android commands

src/cca/manifest.json
includes fix for https://github.com/uProxy/uproxy/issues/2827
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2829)
=> bump android release number

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
Auto-generated by Colab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2836)
=> Bump version numbers to 0.9.12

package.json, src/lib/socks/node/server.ts, src/lib/zork/zork.ts
As discussed. Look forward to your comments!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2837)
=> initial progress toward freedomless zork implementation

src/cca/manifest.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2849)
=> bump android version number

src/chrome/extension/scripts/background.ts
This fixes - ironically - an ordering issue with the variables in the background script introduced here:
https://github.com/uProxy/uproxy/commit/8f512d1c33573bc6635431d4e64c6abb83b4c2a0
(the `no-use-before-declare` tslint rule)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2854)
=> FIX: background script so extension loads

Gruntfile.js, docker/testing/run-scripts/run_pair.sh, package.json, src/lib/socks/bin/webrtc.ts, src/lib/socks/headers.ts, src/lib/socks/session.ts, src/lib/zork/freedom-module.ts, src/lib/zork/index.ts, src/tslint.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2859)
=> fix socks session bookkeeping when there are concurrent sessions + legacy client support from #2858

docker/testing/run-scripts/run_cloud.sh, src/lib/cloud/social/provider.ts, src/lib/zork/index.ts
@jab more of an FYI...a few things to make it easier to deploy a cloud server with this code, as described at https://github.com/uProxy/uproxy/wiki/Cloud-on-Node.js.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2866)
=> a few things to make it easy to deploy cloud servers with this code

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2867)
=> fix the upload paths for tag builds

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2869)
=> Bump version numbers to 0.9.13

bower.json, package.json, src/chrome/app/manifest.json, src/chrome/extension/manifest.json, src/firefox/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2871)
=> Bump version numbers to 0.9.14

install-cloud.sh
Found this very handy when testing out https://github.com/uProxy/uproxy/pull/2868 and the latest release.
Rather than cloning the repo and switching to the development branch, etc., it let me run:
```bash
curl https://raw.githubusercontent.com/uProxy/uproxy/trevj-curl-installer-additions/install-cloud.sh | sh -s -- -u -s uproxy/sshd-alpine -z uproxy/firefox-stable -b trevj-alpine-ssh
```
I think this will be useful in future, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uproxy/uproxy/2872)
=> pass more flags to run_cloud.sh, for easier testing
